/*

 * Note: this file originally auto-generated by mib2c using

 *       : mib2c.array-user.conf,v 5.15.2.1 2003/02/27 05:59:41 rstory Exp $

 *

 * $Id: appMeteringTable.c,v 1.2 2003/12/02 05:20:02 guga Exp $

 *

 *

 * For help understanding NET-SNMP in general, please check the 

 *     documentation and FAQ at:

 *

 *     http://www.net-snmp.org/

 *

 *

 * For help understanding this code, the agent and how it processes

 *     requests, please check the following references.

 *

 *     http://www.net-snmp.org/tutorial/

 *

 *

 * You can also join the #net-snmp channel on irc.openprojects.net

 *     and ask for help there.

 *

 *

 * And if all else fails, send a detailed message to the developers

 *     describing the problem you are having to:

 *

 *    net-snmp-coders@lists.sourceforge.net

 *

 *

 * Yes, there is lots of code here that you might not use. But it is much

 * easier to remove code than to add it!

 */

#include <net-snmp/net-snmp-config.h>

#include <net-snmp/net-snmp-includes.h>

#include <net-snmp/agent/net-snmp-agent-includes.h>



#include <net-snmp/library/snmp_assert.h>



#include "appMeteringTable.h"



static     netsnmp_handler_registration *my_handler = NULL;

static     netsnmp_table_array_callbacks cb;



oid appMeteringTable_oid[] = { appMeteringTable_TABLE_OID };

size_t appMeteringTable_oid_len = OID_LENGTH(appMeteringTable_oid);

stVarBindArgs stAppTrap_Var[APP_NO_OF_FIELDS];

char cBinaryName[APP_MAX_VAR_LEN];

char cBinaryOID[APP_MAX_OID_LEN]; 

#ifdef appMeteringTable_IDX2

/************************************************************

 * keep binary tree to find context by name

 */

static int appMeteringTable_cmp( const void *lhs, const void *rhs );

int appMeteringTable_Search_Index_From_File (short iCurrIndex, short *strapCount ); 



/************************************************************

 * compare two context pointers here. Return -1 if lhs < rhs,

 * 0 if lhs == rhs, and 1 if lhs > rhs.

 */

static int

appMeteringTable_cmp( const void *lhs, const void *rhs )

{

    appMeteringTable_context *context_l =

        (appMeteringTable_context *)lhs;

    appMeteringTable_context *context_r =

        (appMeteringTable_context *)rhs;



    /*

     * check primary key, then secondary. Add your own code if

     * there are more than 2 indexes

     */

    //int rc;



    /*

     * TODO: implement compare. Remove this ifdef code and

     * add your own code here.

     */

#ifdef TABLE_CONTAINER_TODO

    snmp_log(LOG_ERR,

             "appMeteringTable_compare not implemented! Container order undefined\n" );

    return 0;

#endif

    

    /*

     * EXAMPLE:

     *   

     * rc = strcmp( context_l->xxName, context_r->xxName);

     *

     * if(rc)

     *   return rc;

     *

     * TODO: fix secondary keys (or delete if there are none)

     *

     * if(context_l->yy < context_r->yy) 

     *   return -1;

     *

     * return (context_l->yy == context_r->yy) ? 0 : 1;

     */

}



/************************************************************

 * search tree

 */

/** TODO: set additional indexes as parameters */

appMeteringTable_context *

appMeteringTable_get( const char *name, int len )

{

    //appMeteringTable_context tmp;



    /** we should have a secondary index */

    netsnmp_assert(cb.container->next != NULL);

    

    /*

     * TODO: implement compare. Remove this ifdef code and

     * add your own code here.

     */

#ifdef TABLE_CONTAINER_TODO

    snmp_log(LOG_ERR, "appMeteringTable_get not implemented!\n" );

    return NULL;

#endif

    /*

     * EXAMPLE:

     *

     * if(len > sizeof(tmp.xxName))

     *   return NULL;

     *

     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );

     * tmp.xxName_len = len;

     *

     * return CONTAINER_FIND(cb.container->next, &tmp);

     */

}

#endif





/************************************************************

 * Initializes the appMeteringTable module

 */

void

init_appMeteringTable(void)

{

    initialize_table_appMeteringTable();



    /*

     * TODO: perform any startup stuff here

     */

    appMeteringTable_Load_Container_From_File ();



}

/************************************************************

 * the *_row_copy routine

 */

static int appMeteringTable_row_copy(appMeteringTable_context * dst,

                         appMeteringTable_context * src)

{

    if(!dst||!src)

        return 1;

        

    /*

     * copy index, if provided

     */

    if(dst->index.oids)

        free(dst->index.oids);

    if(snmp_clone_mem( (void*)&dst->index.oids, src->index.oids,

                           src->index.len * sizeof(oid) )) {

        dst->index.oids = NULL;

        return 1;

    }

    dst->index.len = src->index.len;

    



    /*

     * copy components into the context structure

     */

    dst->appMeteringIndex = src->appMeteringIndex;



    memcpy( dst->appMeteringID, src->appMeteringID, src->appMeteringID_len );

    dst->appMeteringID_len = src->appMeteringID_len;



    memcpy( dst->appMeteringName, src->appMeteringName, src->appMeteringName_len );

    dst->appMeteringName_len = src->appMeteringName_len;



    memcpy( dst->appMeteringDescription, src->appMeteringDescription, src->appMeteringDescription_len );

    dst->appMeteringDescription_len = src->appMeteringDescription_len;



    memcpy( dst->appMeteringCreatedDateTime, src->appMeteringCreatedDateTime, src->appMeteringCreatedDateTime_len );

    dst->appMeteringCreatedDateTime_len = src->appMeteringCreatedDateTime_len;



    memcpy( dst->appMeteringCreatedUserID, src->appMeteringCreatedUserID, src->appMeteringCreatedUserID_len );

    dst->appMeteringCreatedUserID_len = src->appMeteringCreatedUserID_len;



    memcpy( dst->appMeteringCreatedUserName, src->appMeteringCreatedUserName, src->appMeteringCreatedUserName_len );

    dst->appMeteringCreatedUserName_len = src->appMeteringCreatedUserName_len;



    memcpy( dst->appMeteringStartTime, src->appMeteringStartTime, src->appMeteringStartTime_len );

    dst->appMeteringStartTime_len = src->appMeteringStartTime_len;



    memcpy( dst->appMeteringEndTime, src->appMeteringEndTime, src->appMeteringEndTime_len );

    dst->appMeteringEndTime_len = src->appMeteringEndTime_len;



    dst->appMeteringReaction = src->appMeteringReaction;



    dst->appMeteringStatus = src->appMeteringStatus;



    memcpy( dst->appMeteringLastUpdatedDateAndTime, src->appMeteringLastUpdatedDateAndTime, src->appMeteringLastUpdatedDateAndTime_len );

    dst->appMeteringLastUpdatedDateAndTime_len = src->appMeteringLastUpdatedDateAndTime_len;



    memcpy( dst->appMeteringApplicationName, src->appMeteringApplicationName, src->appMeteringApplicationName_len );

    dst->appMeteringApplicationName_len = src->appMeteringApplicationName_len;



    memcpy( dst->appMeteringUserName, src->appMeteringUserName, src->appMeteringUserName_len );

    dst->appMeteringUserName_len = src->appMeteringUserName_len;



    memcpy( dst->appMeteringBinaryName, src->appMeteringBinaryName, src->appMeteringBinaryName_len );

    dst->appMeteringBinaryName_len = src->appMeteringBinaryName_len;



    memcpy( dst->appMeteringAlertMessage, src->appMeteringAlertMessage, src->appMeteringAlertMessage_len );

    dst->appMeteringAlertMessage_len = src->appMeteringAlertMessage_len;



    return 0;

}



#ifdef appMeteringTable_SET_HANDLING



/*

 * the *_extract_index routine

 */

int

appMeteringTable_extract_index( appMeteringTable_context * ctx, netsnmp_index * hdr )

{

    /*

     * temporary local storage for extracting oid index

     */

    netsnmp_variable_list var_appMeteringIndex;

    int err;



    /*

     * copy index, if provided

     */

    if(hdr) {

        netsnmp_assert(ctx->index.oids == NULL);

        if(snmp_clone_mem( (void*)&ctx->index.oids, hdr->oids,

                           hdr->len * sizeof(oid) )) {

            return -1;

        }

        ctx->index.len = hdr->len;

    }



    /**

     * Create variable to hold each component of the index

     */

       memset( &var_appMeteringIndex, 0x00, sizeof(var_appMeteringIndex) );

       var_appMeteringIndex.type = ASN_UNSIGNED;

       /** TODO: link this index to the next, or NULL for the last one */

#ifdef TABLE_CONTAINER_TODO

    snmp_log(LOG_ERR, "appMeteringTable_extract_index index list not implemented!\n" );

   

    return 0;

#else

      // var_appMeteringIndex.next_variable = &var_XX;

#endif





    /*

     * parse the oid into the individual components

     */

    err = parse_oid_indexes( hdr->oids, hdr->len, &var_appMeteringIndex );

    if (err == SNMP_ERR_NOERROR) {

       /*

        * copy components into the context structure

        */

                ctx->appMeteringIndex = *var_appMeteringIndex.val.integer;

#ifdef APP_DEBUG

		printf("Value of index: %d\n",*var_appMeteringIndex.val.integer);

#endif

   

           /*

            * TODO: check index for valid values. For EXAMPLE:

            *

              * if ( *var_appMeteringIndex.val.integer != XXX ) {

          *    err = -1;

          * }

          */

    }



    /*

     * parsing may have allocated memory. free it.

     */

    snmp_reset_var_buffers( &var_appMeteringIndex );



    return err;

}



/************************************************************

 * the *_can_activate routine is called

 * when a row is changed to determine if all the values

 * set are consistent with the row's rules for a row status

 * of ACTIVE.

 *

 * return 1 if the row could be ACTIVE

 * return 0 if the row is not ready for the ACTIVE state

 */

int appMeteringTable_can_activate(appMeteringTable_context *undo_ctx,

                      appMeteringTable_context *row_ctx,

                      netsnmp_request_group * rg)

{

    /*

     * TODO: check for activation requirements here

     */

    return 1;

}



/************************************************************

 * the *_can_deactivate routine is called when a row that is

 * currently ACTIVE is set to a state other than ACTIVE. If

 * there are conditions in which a row should not be allowed

 * to transition out of the ACTIVE state (such as the row being

 * referred to by another row or table), check for them here.

 *

 * return 1 if the row can be set to a non-ACTIVE state

 * return 0 if the row must remain in the ACTIVE state

 */

int appMeteringTable_can_deactivate(appMeteringTable_context *undo_ctx,

                        appMeteringTable_context *row_ctx,

                        netsnmp_request_group * rg)

{

    /*

     * TODO: check for deactivation requirements here

     */

    return 1;

}



/************************************************************

 * the *_can_delete routine is called to determine if a row

 * can be deleted.

 *

 * return 1 if the row can be deleted

 * return 0 if the row cannot be deleted

 */

int appMeteringTable_can_delete(appMeteringTable_context *undo_ctx,

                    appMeteringTable_context *row_ctx,

                    netsnmp_request_group * rg)

{

    /*

     * probably shouldn't delete a row that we can't

     * deactivate.

     */

    if(appMeteringTable_can_deactivate(undo_ctx,row_ctx,rg) != 1)

        return 0;

    

    /*

     * TODO: check for other deletion requirements here

     */

    return 1;

}



#ifdef appMeteringTable_ROW_CREATION

/************************************************************

 * the *_create_row routine is called by the table handler

 * to create a new row for a given index. If you need more

 * information (such as column values) to make a decision

 * on creating rows, you must create an initial row here

 * (to hold the column values), and you can examine the

 * situation in more detail in the *_set_reserve1 or later

 * states of set processing. Simple check for a NULL undo_ctx

 * in those states and do detailed creation checking there.

 *

 * returns a newly allocated appMeteringTable_context

 *   structure if the specified indexes are not illegal

 * returns NULL for errors or illegal index values.

 */

appMeteringTable_context *

appMeteringTable_create_row( netsnmp_index* hdr)

{

    appMeteringTable_context * ctx =

        SNMP_MALLOC_TYPEDEF(appMeteringTable_context);

    if(!ctx)

        return NULL;

        

    /*

     * TODO: check indexes, if necessary.

     */

    if(appMeteringTable_extract_index( ctx, hdr )) {

        free(ctx->index.oids);

        free(ctx);

        return NULL;

    }



    /* netsnmp_mutex_init(ctx->lock);

       netsnmp_mutex_lock(ctx->lock); */



    /*

     * TODO: initialize any default values here. This is also

     * first place you really should allocate any memory for

     * yourself to use.  If you allocated memory earlier,

     * make sure you free it for earlier error cases!

     */

    /**

     ctx->appMeteringID = 0;

     ctx->appMeteringName = 0;

     ctx->appMeteringDescription = 0;

     ctx->appMeteringCreatedDateTime = 0;

     ctx->appMeteringCreatedUserID = 0;

     ctx->appMeteringCreatedUserName = 0;

     ctx->appMeteringStartTime = 0;

     ctx->appMeteringEndTime = 0;

     ctx->appMeteringReaction = 0;

     ctx->appMeteringStatus = 0;

     ctx->appMeteringLastUpdatedDateAndTime = 0;

     ctx->appMeteringApplicationName = 0;

     ctx->appMeteringUserName = 0;

     ctx->appMeteringBinaryName = 0;

     ctx->appMeteringAlertMessage = 0;

    */



    return ctx;

}

#endif



/************************************************************

 * the *_duplicate row routine

 */

appMeteringTable_context *

appMeteringTable_duplicate_row( appMeteringTable_context * row_ctx)

{

    appMeteringTable_context * dup;



    if(!row_ctx)

        return NULL;



    dup = SNMP_MALLOC_TYPEDEF(appMeteringTable_context);

    if(!dup)

        return NULL;

        

    if(appMeteringTable_row_copy(dup,row_ctx)) {

        free(dup);

        dup = NULL;

    }



    return dup;

}



/************************************************************

 * the *_delete_row method is called to delete a row.

 */

netsnmp_index * appMeteringTable_delete_row( appMeteringTable_context * ctx )

{

  /* netsnmp_mutex_destroy(ctx->lock); */



    if(ctx->index.oids)

        free(ctx->index.oids);



    /*

     * TODO: release any memory you allocated here...

     */



    /*

     * release header

     */

    free( ctx );



    return NULL;

}





/************************************************************

 * RESERVE is used to check the syntax of all the variables

 * provided, that the values being set are sensible and consistent,

 * and to allocate any resources required for performing the SET.

 * After this stage, the expectation is that the set ought to

 * succeed, though this is not guaranteed. (In fact, with the UCD

 * agent, this is done in two passes - RESERVE1, and

 * RESERVE2, to allow for dependancies between variables).

 *

 * BEFORE calling this routine, the agent will call duplicate_row

 * to create a copy of the row (unless this is a new row; i.e.

 * row_created == 1).

 *

 * next state -> SET_RESERVE2 || SET_FREE

 */

void appMeteringTable_set_reserve1( netsnmp_request_group *rg )

{

    appMeteringTable_context *row_ctx =

            (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx =

            (appMeteringTable_context *)rg->undo_info;

    netsnmp_variable_list *var;

    netsnmp_request_group_item *current;

    int rc;





    /*

     * TODO: loop through columns, check syntax and lengths. For

     * columns which have no dependencies, you could also move

     * the value/range checking here to attempt to catch error

     * cases as early as possible.

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;

        rc = SNMP_ERR_NOERROR;



        switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringID)

var->val_len);

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringName)

var->val_len);

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringDescription)

var->val_len);

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringCreatedDateTime)

var->val_len);

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringCreatedUserID)

var->val_len);

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringCreatedUserName)

var->val_len);

        break;



        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringStartTime)

var->val_len);

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringEndTime)

var->val_len);

        break;



        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,

                                                sizeof(row_ctx->appMeteringReaction));

        break;



        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,

                                                sizeof(row_ctx->appMeteringStatus));

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringLastUpdatedDateAndTime)

var->val_len);

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringApplicationName)

var->val_len);

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringUserName)

var->val_len);

        break;



        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                                //sizeof(row_ctx->appMeteringBinaryName)

var->val_len);

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,

                                               // sizeof(row_ctx->appMeteringAlertMessage)

var->val_len);

        break;



        default: /** We shouldn't get here */

            rc = SNMP_ERR_GENERR;

            snmp_log(LOG_ERR, "unknown column in "

                     "appMeteringTable_set_reserve1\n");

        }



        if (rc)

           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc );

        rg->status = SNMP_MAX( rg->status, current->ri->status );

    }



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

}



void appMeteringTable_set_reserve2( netsnmp_request_group *rg )

{

    appMeteringTable_context *row_ctx = (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx = (appMeteringTable_context *)rg->undo_info;

    netsnmp_request_group_item *current;

    netsnmp_variable_list *var;

    int rc;



    rg->rg_void = rg->list->ri;



    /*

     * TODO: loop through columns, check for valid

     * values and any range constraints.

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;

        rc = SNMP_ERR_NOERROR;



        switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( *var->val.integer != XXX ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

                rc = netsnmp_check_vb_rowstatus(current->ri->requestvb,

                                                undo_ctx ?

                                                undo_ctx->appMeteringStatus:0);

                rg->rg_void = current->ri;

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

                    /*

                     * TODO: routine to check valid values

                     *

                     * EXAMPLE:

                     *

                    * if ( XXX_check_value( var->val.string, XXX ) ) {

                *    rc = SNMP_ERR_INCONSISTENTVALUE;

                *    rc = SNMP_ERR_BADVALUE;

                * }

                */

        break;



        default: /** We shouldn't get here */

            netsnmp_assert(0); /** why wasn't this caught in reserve1? */

        }



        if (rc)

           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);

    }



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

}



/************************************************************

 * Assuming that the RESERVE phases were successful, the next

 * stage is indicated by the action value ACTION. This is used

 * to actually implement the set operation. However, this must

 * either be done into temporary (persistent) storage, or the

 * previous value stored similarly, in case any of the subsequent

 * ACTION calls fail.

 *

 * In your case, changes should be made to row_ctx. A copy of

 * the original row is in undo_ctx.

 */

void appMeteringTable_set_action( netsnmp_request_group *rg )

{

    char ctmpOID[APP_MAX_OID_LEN]=".1.3.6.1.4.1.3204.1.3.34.3.1.15.";

    char tmp[5];

    time_t stTime;

    netsnmp_variable_list *var;

    appMeteringTable_context *row_ctx = (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx = (appMeteringTable_context *)rg->undo_info;

    netsnmp_request_group_item *current;



    int            row_err = 0;

    

   /*Get the updated Date and Time*/

   memset(row_ctx->appMeteringLastUpdatedDateAndTime,'\0',APP_MAX_DT_LEN);

   row_ctx->appMeteringLastUpdatedDateAndTime_len = APP_MAX_DT_LEN;

   (void *) time(&stTime);

    strcpy(row_ctx->appMeteringLastUpdatedDateAndTime , (u_char *) date_n_time(&stTime, (size_t *)&(row_ctx->appMeteringLastUpdatedDateAndTime_len)));

    

    /*

     * TODO: loop through columns, copy varbind values

     * to context structure for the row.

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;



        switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringID,var->val.string,var->val_len);

            row_ctx->appMeteringID_len = var->val_len;

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringName,var->val.string,var->val_len);

            row_ctx->appMeteringName_len = var->val_len;

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringDescription,var->val.string,var->val_len);

            row_ctx->appMeteringDescription_len = var->val_len;

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringCreatedDateTime,var->val.string,var->val_len);

            row_ctx->appMeteringCreatedDateTime_len = var->val_len;

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringCreatedUserID,var->val.string,var->val_len);

            row_ctx->appMeteringCreatedUserID_len = var->val_len;

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringCreatedUserName,var->val.string,var->val_len);

            row_ctx->appMeteringCreatedUserName_len = var->val_len;

        break;



        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringStartTime,var->val.string,var->val_len);

            row_ctx->appMeteringStartTime_len = var->val_len;

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringEndTime,var->val.string,var->val_len);

            row_ctx->appMeteringEndTime_len = var->val_len;

        break;



        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

            row_ctx->appMeteringReaction = *var->val.integer;

        break;



        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

            row_ctx->appMeteringStatus = *var->val.integer;

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringLastUpdatedDateAndTime,var->val.string,var->val_len);

            row_ctx->appMeteringLastUpdatedDateAndTime_len = var->val_len;

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringApplicationName,var->val.string,var->val_len);

            row_ctx->appMeteringApplicationName_len = var->val_len;

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringUserName,var->val.string,var->val_len);

            row_ctx->appMeteringUserName_len = var->val_len;

        break;



        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringBinaryName,var->val.string,var->val_len);

            row_ctx->appMeteringBinaryName_len = var->val_len;

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

            memcpy(row_ctx->appMeteringAlertMessage,var->val.string,var->val_len);

            row_ctx->appMeteringAlertMessage_len = var->val_len;

        break;



        default: /** We shouldn't get here */

            netsnmp_assert(0); /** why wasn't this caught in reserve1? */

        }

    }



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

#ifndef appMeteringTable_CAN_MODIFY_ACTIVE_ROW

    if( undo_ctx && RS_IS_ACTIVE(undo_ctx->appMeteringStatus) &&

        row_ctx && RS_IS_ACTIVE(row_ctx->appMeteringStatus) ) {

            row_err = 1;

    }

#endif



     



    /*

     * check activation/deactivation

     */

    row_err = netsnmp_table_array_check_row_status(&cb, rg,

                                  row_ctx ? &row_ctx->appMeteringStatus : NULL,

                                  undo_ctx ? &undo_ctx->appMeteringStatus : NULL);

    if(row_err) {

        netsnmp_set_mode_request_error(MODE_SET_BEGIN,

                                       (netsnmp_request_info*)rg->rg_void,

                                       row_err);

        return;

    }



    if((row_ctx->appMeteringStartTime_len==0 ||

	row_ctx->appMeteringEndTime_len==0 ||

        row_ctx->appMeteringBinaryName_len==0) &&

	(row_ctx->appMeteringStatus==4 ||

		row_ctx->appMeteringStatus==1)) {

#ifdef APP_DEBUG

	     printf("Inside if of set-action\n");	

#endif

	     row_err = 1;

   }//end of if



   if(row_err) {

        netsnmp_set_mode_request_error(MODE_SET_BEGIN,

                                     rg->list->ri ,

                                       row_err);

        return;

    }//end of if





    /*

     * TODO: if you have dependencies on other tables, this would be

     * a good place to check those, too.

     */

if(row_ctx->appMeteringStatus == 6){

   memset(cBinaryName,'\0',APP_MAX_VAR_LEN);

   memcpy(cBinaryName,row_ctx->appMeteringBinaryName,row_ctx->appMeteringBinaryName_len);

   memset(cBinaryOID,'\0',APP_MAX_OID_LEN);

   memset(tmp,'\0',5);

   sprintf(tmp,"%d",row_ctx->appMeteringIndex);

   strcat(ctmpOID,tmp); 

   memcpy(cBinaryOID,ctmpOID,strlen(ctmpOID));

  #ifdef APP_DEBUG

    printf("Inside Set_Action: %s\n",cBinaryName);

  #endif

}

}



/************************************************************

 * Only once the ACTION phase has completed successfully, can

 * the final COMMIT phase be run. This is used to complete any

 * writes that were done into temporary storage, and then release

 * any allocated resources. Note that all the code in this phase

 * should be "safe" code that cannot possibly fail (cue

 * hysterical laughter). The whole intent of the ACTION/COMMIT

 * division is that all of the fallible code should be done in

 * the ACTION phase, so that it can be backed out if necessary.

 *

 * BEFORE calling this routine, the agent will update the

 * container (inserting a row if row_created == 1, or removing

 * the row if row_deleted == 1).

 *

 * AFTER calling this routine, the agent will delete the

 * undo_info.

 */

void appMeteringTable_set_commit( netsnmp_request_group *rg )

{

    FILE *fp=NULL;

    char acstrTmpOID[APP_MAX_VAR_LEN];

    short iIndex;

    short UsrNameStatus = 0; 

    short srecCount = 0;

    stVarBindArgs stargs[APP_NO_OF_FIELDS];

    short sRowStatus = 0;

    short icnt;

    short subcnt;

    short sSet=0;

    short sAction = 0;

    short tmpCount;    

    short srowStatusFlag = 0;

    short strapCount = 0;

    netsnmp_variable_list *var;

    appMeteringTable_context *ctx = NULL; 

    appMeteringTable_context *row_ctx = (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx = (appMeteringTable_context *)rg->undo_info;

    netsnmp_request_group_item *current;

    time_t now;


        
    if ( strlen(row_ctx->appMeteringCreatedDateTime) == 0 )
	{
		// Get the Date-Time in time_t format
		// and update the created time for the newly
		// created row
		(void *) time(&now);
		strcpy(row_ctx->appMeteringCreatedDateTime,
		(u_char *) date_n_time(&now,
		(size_t*)&(row_ctx->appMeteringCreatedDateTime_len)));
	}

    /*Load the Record in a File*/




   fp = fopen (APP_CONTAINER_FILE, "wb");

   if (fp == (FILE *) NULL)

   {

#ifdef APP_DEBUG

       printf("appMeteringTable_set_commit",

                    "Couldn't open CONTAINER_FILE\n");

#endif

        return;

   }//end of if

   ctx = CONTAINER_FIRST(cb.container);

   if (ctx)

   {

	/* Assign ctx index->oids to idx */

        ctx->idx = (unsigned long) *ctx->index.oids;

	   



       if (fwrite (ctx, sizeof (appMeteringTable_context), 1, fp) != 1)

       {

#ifdef APP_DEBUG

           printf("appMeteringTable_set_commit",

                       "1 write ctx error\n");

#endif

	   fclose(fp);

           return;

       }//end of if (fwrite)

    }//end of if (ctx)



    while (ctx)

    {

        ctx = CONTAINER_NEXT(cb.container,ctx);

        if(ctx)

        {

		

            /* Assign ctx index->oids to idx */

            ctx->idx = (unsigned long) *ctx->index.oids;

           

	    if (fwrite (ctx, sizeof (appMeteringTable_context), 1, fp) != 1)

            {

#ifdef APP_DEBUG

               printf("appMeteringTable_set_commit",

                           "2 write ctx error \n");

#endif

               return;

            }//end of if (fwrite)

        }//end of if (ctx)

    }//end of while (ctx)



    fclose (fp);



	





   /*

     * loop through columns

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;

	memset(acstrTmpOID,'\0',APP_MAX_VAR_LEN);

        //strcpy(acstrTmpOID,"");

        memset(stargs[srecCount].acVariable,0,sizeof(stargs[srecCount].acVariable));

        for(icnt=0;icnt<var->name_length;icnt++)

        {

          sprintf(acstrTmpOID, ".%lu",var->name[icnt]);

          strcat (stargs[srecCount].acVariable,acstrTmpOID);

        }//for icnt

#ifdef APP_DEBUG

	printf("variable: %s\n",stargs[srecCount].acVariable);	

#endif

	sprintf(acstrTmpOID,"%lu",var->name[(var->name_length-1)]);

	iIndex = atoi(acstrTmpOID);

#ifdef APP_DEBUG

	printf("Index value is %d\n",iIndex);

    //printf("Value of of acstrTmpOID: %c\n",acstrTmpOID);

#endif

    switch ((short) var->type)

    {

       case ASN_INTEGER:

          stargs[srecCount].cType='i';

#ifdef APP_DEBUG

          printf("Type is integer : %d\n",(short) var->type);

          printf("Value: %d\n",*(var->val.integer));

#endif

          memset (stargs[srecCount].pcValue, '\0', sizeof (stargs[srecCount].pcValue));

          sprintf (stargs[srecCount].pcValue, "%ld",  *(var->val.integer));

#ifdef APP_DEBUG

          printf("****** After copying args[%d].pcValue=%s\n",

                    srecCount, stargs[srecCount].pcValue);

#endif

       break;



       case ASN_OCTET_STR:

          stargs[srecCount].cType='s';

#ifdef APP_DEBUG

          printf("Type is an OCTET string\n");

#endif

         // printf("%d\n",(short) var->type);

          //printf("Value: %s\n",var->val.string);

          memset (stargs[srecCount].pcValue,'\0',sizeof (stargs[srecCount].pcValue));

          memcpy (stargs[srecCount].pcValue, var->val.string,var->val_len);

#ifdef APP_DEBUG

          printf("Value after copying: %s\n",stargs[srecCount].pcValue);

#endif

       break;



       default:

#ifdef APP_DEBUG

          printf ("WARNING: TYPE NOT HANDLED....\n");

#endif

       break;

    }//switch         

        



    switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGSTARTTIME:

	    sSet++;

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

	    sSet++; 

        break;



        case COLUMN_APPMETERINGREACTION:

#ifdef APP_DEBUG

            printf("Inside Reaction: \n");

#endif

            sSet++;

            /** INTEGER = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGSTATUS:

#ifdef APP_DEBUG

             printf("ROwstatus\n");

#endif

             sRowStatus = atoi(stargs[srecCount].pcValue);

	    /* RowStatus = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

#ifdef APP_DEBUG

             printf("Inside appMetering\n");  

#endif

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

             UsrNameStatus = 1;

        break;



        case COLUMN_APPMETERINGBINARYNAME:

             sSet++;

#ifdef APP_DEBUG

             printf("Inside BinaryName\n");

#endif

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

        break;



        default: /** We shouldn't get here */

            netsnmp_assert(0); /** why wasn't this caught in reserve1? */

        }//end of switch

        srecCount++;

    }//end of for

    

#ifdef APP_DEBUG    	    

    printf("Value of set: %d\n",sSet);

#endif

    if(UsrNameStatus ==1){

      #ifdef APP_DEBUG

    printf("Inside username trap avoiding\n");

#endif



       return;

    }



       /*Send Trap only when the mandatory fields are set*/

        switch (sRowStatus){

	   case APP_ROW_CREATE:

               if (sSet==4){

#ifdef APP_DEBUG

                   printf("Inside Sending Trap\n");

#endif

		   sAction = APP_TRAP; 

               }//if

	       break;

	   case APP_ROW_DELETE:

#ifdef APP_DEBUG

	      printf("Inside Row Delete\n");

#endif

                 memset (stargs[srecCount].acVariable,'\0',APP_MAX_OID_LEN);

                 memcpy (stargs[srecCount].acVariable,cBinaryOID,strlen(cBinaryOID));



                 stargs[srecCount].cType ='s' ;



                 memset (stargs[srecCount].pcValue,'\0',APP_MAX_VAR_LEN);

                 memcpy (stargs[srecCount].pcValue,cBinaryName,strlen(cBinaryName));

                 srecCount++;

#ifdef APP_DEBUG

     printf("OID:%s\n",stargs[srecCount].acVariable);

     printf("VAlue:%s\n",stargs[srecCount].pcValue);

#endif



	      sAction = APP_TRAP;   

              break; 

	    default:

#ifdef APP_DEBUG

	       printf("Inside Modify value of index: %d\n",iIndex);

#endif

               	tmpCount = srecCount; 

#ifdef APP_DEBUG

	        printf("srecCpount /Before calling search: %d\n",srecCount);	

#endif

	        if(appMeteringTable_Search_Index_From_File (iIndex, &strapCount) == APP_SUCCESS)

	        {

#ifdef APP_DEBUG

		   printf("Trapcount :%d\n",strapCount);	

#endif

                   for(icnt = 0;icnt<strapCount;icnt++)

		   {

		       for(subcnt =0;subcnt<tmpCount;subcnt++)

		       {

#ifdef APP_DEBUG

			  printf("stargs[%d].value: %s\n",subcnt,stargs[subcnt].acVariable);

			  printf("stAppTrap[%d].value: %s\n",icnt,stAppTrap_Var[icnt].acVariable);

#endif

			  if (strcmp(stAppTrap_Var[icnt].acVariable,stargs[subcnt].acVariable) == 0){

#ifdef APP_DEBUG

                            printf("Inside Compare\n");		  

#endif

			    break;

			  }

		       }

                        if(subcnt == tmpCount)

			{

#ifdef APP_DEBUG

			printf("Inside modify loop-srecCount: %d\n",srecCount);  

#endif

	                memset (stargs[srecCount].acVariable,'\0',APP_MAX_OID_LEN);

                        memcpy (stargs[srecCount].acVariable,stAppTrap_Var[icnt].acVariable,

				       strlen(stAppTrap_Var[icnt].acVariable));



			stargs[srecCount].cType = stAppTrap_Var[icnt].cType;	

			    

		        memset (stargs[srecCount].pcValue,'\0',APP_MAX_VAR_LEN);

                        memcpy (stargs[srecCount].pcValue,stAppTrap_Var[icnt].pcValue,

		      		       strlen(stAppTrap_Var[icnt].pcValue));

			srecCount++;

			}

	          }//end of for icnt



                  sAction = APP_TRAP;

	       }//end of check      

	       break;

	}//switch

#ifdef APP_DEBUG

	printf("SRecCount after modify: %d\n",srecCount);

#endif

        for(icnt =0;icnt<srecCount;icnt++){

#ifdef APP_DEBUG

	       printf("OID inside trap: %s\n",stargs[icnt].acVariable);

	       printf("OID Value : %s\n",stargs[icnt].pcValue);

#endif

        }

#ifdef APP_DEBUG	       

        printf("Action: %d\n",sAction);

	printf("RowStatus: %d\n",sRowStatus);

#endif	

        if(sAction == APP_TRAP){

#ifdef APP_DEBUG

           printf("Inside sAction\n");		

#endif

	   appMeteringTable_send_snmptrap(srecCount,stargs,2503);

	}



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

}



/************************************************************

 * If either of the RESERVE calls fail, the write routines

 * are called again with the FREE action, to release any resources

 * that have been allocated. The agent will then return a failure

 * response to the requesting application.

 *

 * AFTER calling this routine, the agent will delete undo_info.

 */

void appMeteringTable_set_free( netsnmp_request_group *rg )

{

    netsnmp_variable_list *var;

    appMeteringTable_context *row_ctx = (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx = (appMeteringTable_context *)rg->undo_info;

    netsnmp_request_group_item *current;



    /*

     * loop through columns

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;



        switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

        break;



        default: /** We shouldn't get here */

            /** should have been logged in reserve1 */

	break;  

        }

    }



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

}



/************************************************************

 * If the ACTION phase does fail (for example due to an apparently

 * valid, but unacceptable value, or an unforeseen problem), then

 * the list of write routines are called again, with the UNDO

 * action. This requires the routine to reset the value that was

 * changed to its previous value (assuming it was actually changed),

 * and then to release any resources that had been allocated. As

 * with the FREE phase, the agent will then return an indication

 * of the error to the requesting application.

 *

 * BEFORE calling this routine, the agent will update the container

 * (remove any newly inserted row, re-insert any removed row).

 *

 * AFTER calling this routing, the agent will call row_copy

 * to restore the data in existing_row from the date in undo_info.

 * Then undo_info will be deleted (or existing row, if row_created

 * == 1).

 */

void appMeteringTable_set_undo( netsnmp_request_group *rg )

{

    netsnmp_variable_list *var;

    appMeteringTable_context *row_ctx = (appMeteringTable_context *)rg->existing_row;

    appMeteringTable_context *undo_ctx = (appMeteringTable_context *)rg->undo_info;

    netsnmp_request_group_item *current;



    /*

     * loop through columns

     */

    for( current = rg->list; current; current = current->next ) {



        var = current->ri->requestvb;



        switch(current->tri->colnum) {



        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

        break;



        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

        break;



        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

        break;



        default: /** We shouldn't get here */

            netsnmp_assert(0); /** why wasn't this caught in reserve1? */

	    break;

        }

    }



    /*

     * done with all the columns. Could check row related

     * requirements here.

     */

}



#endif /** appMeteringTable_SET_HANDLING */





/************************************************************

 *

 * Initialize the appMeteringTable table by defining its contents and how it's structured

 */

void

initialize_table_appMeteringTable(void)

{

    netsnmp_table_registration_info *table_info;



    if(my_handler) {

        snmp_log(LOG_ERR, "initialize_table_appMeteringTable_handler called again\n");

        return;

    }



    memset(&cb, 0x00, sizeof(cb));



    /** create the table structure itself */

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);



    /* if your table is read only, it's easiest to change the

       HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY */

    my_handler = netsnmp_create_handler_registration("appMeteringTable",

                                             netsnmp_table_array_helper_handler,

                                             appMeteringTable_oid,

                                             appMeteringTable_oid_len,

                                             HANDLER_CAN_RWRITE);

            

    if (!my_handler || !table_info) {

        snmp_log(LOG_ERR, "malloc failed in "

                 "initialize_table_appMeteringTable_handler\n");

        return; /** mallocs failed */

    }



    /***************************************************

     * Setting up the table's definition

     */

    /*

     * TODO: add any external indexes here.

     */



    /*

     * internal indexes

     */

        /** index: appMeteringIndex */

        netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);



    table_info->min_column = appMeteringTable_COL_MIN;

    table_info->max_column = appMeteringTable_COL_MAX;



    /***************************************************

     * registering the table with the master agent

     */

    cb.get_value = appMeteringTable_get_value;

    cb.container = netsnmp_container_find("appMeteringTable_primary:"

                                          "appMeteringTable:"

                                          "table_container");

#ifdef appMeteringTable_IDX2

    

    netsnmp_container_add_index(cb.container,

                                netsnmp_container_find("appMeteringTable_secondary:"

                                                       "appMeteringTable:"

                                                       "table_container"));

    cb.container->next->compare = appMeteringTable_cmp;

#endif

#ifdef appMeteringTable_SET_HANDLING

    cb.can_set = 1;

#ifdef appMeteringTable_ROW_CREATION

    cb.create_row = (UserRowMethod*)appMeteringTable_create_row;

#endif

    cb.duplicate_row = (UserRowMethod*)appMeteringTable_duplicate_row;

    cb.delete_row = (UserRowMethod*)appMeteringTable_delete_row;

    cb.row_copy = (Netsnmp_User_Row_Operation *)appMeteringTable_row_copy;



    cb.can_activate = (Netsnmp_User_Row_Action *)appMeteringTable_can_activate;

    cb.can_deactivate = (Netsnmp_User_Row_Action *)appMeteringTable_can_deactivate;

    cb.can_delete = (Netsnmp_User_Row_Action *)appMeteringTable_can_delete;



    cb.set_reserve1 = appMeteringTable_set_reserve1;

    cb.set_reserve2 = appMeteringTable_set_reserve2;

    cb.set_action = appMeteringTable_set_action;

    cb.set_commit = appMeteringTable_set_commit;

    cb.set_free = appMeteringTable_set_free;

    cb.set_undo = appMeteringTable_set_undo;

#endif

    DEBUGMSGTL(("initialize_table_appMeteringTable",

                "Registering table appMeteringTable "

                "as a table array\n"));

    netsnmp_table_container_register(my_handler, table_info, &cb,

                                     cb.container, 1);

}



/************************************************************

 * appMeteringTable_get_value

 */

int appMeteringTable_get_value(

            netsnmp_request_info *request,

            netsnmp_index *item,

            netsnmp_table_request_info *table_info )

{

    netsnmp_variable_list *var = request->requestvb;

    appMeteringTable_context *context = (appMeteringTable_context *)item;

    

    //printf("Inside Get\n");



    switch(table_info->colnum) {



        case COLUMN_APPMETERINGINDEX:

            /** UNSIGNED32 = ASN_UNSIGNED */

            snmp_set_var_typed_value(var, ASN_UNSIGNED,

                         (char*)&context->appMeteringIndex,

                         sizeof(context->appMeteringIndex) );

        break;

    

        case COLUMN_APPMETERINGID:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringID,

                         context->appMeteringID_len );

        break;

    

        case COLUMN_APPMETERINGNAME:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringName,

                         context->appMeteringName_len );

        break;

    

        case COLUMN_APPMETERINGDESCRIPTION:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringDescription,

                         context->appMeteringDescription_len );

        break;

    

        case COLUMN_APPMETERINGCREATEDDATETIME:

            /** DateAndTime = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringCreatedDateTime,

                         context->appMeteringCreatedDateTime_len );

        break;

    

        case COLUMN_APPMETERINGCREATEDUSERID:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringCreatedUserID,

                         context->appMeteringCreatedUserID_len );

        break;

    

        case COLUMN_APPMETERINGCREATEDUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringCreatedUserName,

                         context->appMeteringCreatedUserName_len );

        break;

    

        case COLUMN_APPMETERINGSTARTTIME:

            /** DateAndTime = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringStartTime,

                         context->appMeteringStartTime_len );

        break;

    

        case COLUMN_APPMETERINGENDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringEndTime,

                         context->appMeteringEndTime_len );

        break;

    

        case COLUMN_APPMETERINGREACTION:

            /** INTEGER = ASN_INTEGER */

            snmp_set_var_typed_value(var, ASN_INTEGER,

                         (char*)&context->appMeteringReaction,

                         sizeof(context->appMeteringReaction) );

        break;

    

        case COLUMN_APPMETERINGSTATUS:

            /** RowStatus = ASN_INTEGER */

            snmp_set_var_typed_value(var, ASN_INTEGER,

                         (char*)&context->appMeteringStatus,

                         sizeof(context->appMeteringStatus) );

        break;

    

        case COLUMN_APPMETERINGLASTUPDATEDDATEANDTIME:

            /** DateAndTime = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringLastUpdatedDateAndTime,

                         context->appMeteringLastUpdatedDateAndTime_len );

        break;

    

        case COLUMN_APPMETERINGAPPLICATIONNAME:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringApplicationName,

                         context->appMeteringApplicationName_len );

        break;

    

        case COLUMN_APPMETERINGUSERNAME:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringUserName,

                         context->appMeteringUserName_len );

        break;

    

        case COLUMN_APPMETERINGBINARYNAME:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringBinaryName,

                         context->appMeteringBinaryName_len );

        break;

    

        case COLUMN_APPMETERINGALERTMESSAGE:

            /** DisplayString = ASN_OCTET_STR */

            snmp_set_var_typed_value(var, ASN_OCTET_STR,

                         (char*)&context->appMeteringAlertMessage,

                         context->appMeteringAlertMessage_len );

        break;

    

    default: /** We shouldn't get here */

        snmp_log(LOG_ERR, "unknown column in "

                 "appMeteringTable_get_value\n");

        return SNMP_ERR_GENERR;

    }

    return SNMP_ERR_NOERROR;

}



/************************************************************

 * appMeteringTable_get_by_idx

 */

const appMeteringTable_context *

appMeteringTable_get_by_idx(netsnmp_index * hdr)

{

    return (const appMeteringTable_context *)

        CONTAINER_FIND(cb.container, hdr );

}





int appMeteringTable_send_snmptrap (int length, stVarBindArgs *stTrapPDU, int port)

{

    netsnmp_session session, *ss;

    netsnmp_pdu       *pdu;

    in_addr_t       *pdu_in_addr_t;

    oid            name[APP_MAX_OID_LEN];

    size_t         name_length;

    int            arg = 0;

    int            status;

    char       *trap = NULL, *specific = NULL, *description =

    NULL, *agent = NULL;

    //char       *prognam;

    int            exitval = 0;

    int            icnt = 0;

    char**        argv = NULL;

    int            argc = 0;

    //struct in_addr  laddr;

   // netsnmp_variable_list *tempPtr;

    //char * value; 

   // int intValue;

#ifdef APP_DEBUG 

for(icnt=0;icnt<length;icnt++) 

   printf("trapPDU var=%s type=%c val=%s\n", stTrapPDU[icnt].acVariable,

             stTrapPDU[icnt].cType, stTrapPDU[icnt].pcValue);

#endif

    /** initialize session to default values*/

     

    snmp_sess_init (&session);





    /* Initialize session values - DUMMY */

    session.version = SNMP_VERSION_2c;

    session.timeout = 1 * 1000000L;

    session.retries = 3;

    session.community = (unsigned char *) "public";

    session.community_len = strlen (session.community);



     

    session.peername = "localhost";



    /*DEBUGMSGTL(("send_snmptrap", "trapIP=%lu peername=%s trapPort=%ld\n",

                ctx->trapDestinationIP, session.peername, ctx->trapPort));*/



    SOCK_STARTUP;



    session.callback = appMeteringTable_snmp_input;

    session.callback_magic = NULL;



    

    netsnmp_ds_set_int(NETSNMP_DS_LIBRARY_ID, NETSNMP_DS_LIB_DEFAULT_PORT,

               (int) port);



    if (session.version == SNMP_VERSION_3) {

    /*

     * for traps, we use ourselves as the authoritative engine

     * which is really stupid since command line apps don't have a

     * notion of a persistent engine.  Hence, our boots and time

     * values are probably always really wacked with respect to what

     * a manager would like to see.

     *

     * The following should be enough to:

     *

     * 1) prevent the library from doing discovery for engineid & time.

     * 2) use our engineid instead of the remote engineid for

     * authoritative & privacy related operations.

     * 3) The remote engine must be configured with users for our engineID.

     *

     * -- Wes

     */



    /*

     * setup the engineID based on IP addr.     Need a different

     * algorthim here.  This will cause problems with agents on the

     * same machine sending traps.

     */

    setup_engineID(NULL, NULL);



    /*

     * pick our own engineID

     */

    if (session.securityEngineIDLen == 0 ||

        session.securityEngineID == NULL) {

        session.securityEngineID =

        snmpv3_generate_engineID(&session.securityEngineIDLen);

    }

    if (session.contextEngineIDLen == 0 ||

        session.contextEngineID == NULL) {

        session.contextEngineID =

        snmpv3_generate_engineID(&session.contextEngineIDLen);

    }



    /*

     * set boots and time, which will cause problems if this

     * machine ever reboots and a remote trap receiver has cached our

     * boots and time...  I'll cause a not-in-time-window report to

     * be sent back to this machine.

     */

    if (session.engineBoots == 0)

        session.engineBoots = 1;

    if (session.engineTime == 0)    /* not really correct, */

        session.engineTime = get_uptime();    /* but it'll work. Sort of. */

    }



    ss = snmp_open(&session);

    if (ss == NULL) {

    /*

     * diagnose snmp_open errors with the input netsnmp_session pointer

     */

    snmp_sess_perror("snmptrap", &session);



    SOCK_CLEANUP;

    exit(1);

    }



    if (session.version == SNMP_VERSION_1) {

    pdu = snmp_pdu_create(SNMP_MSG_TRAP);

    pdu_in_addr_t = (in_addr_t *) pdu->agent_addr;



    /*if (argv[arg][0] == 0) {



        pdu->enterprise = (oid *) malloc(sizeof(objid_enterprise));

        memcpy(pdu->enterprise, objid_enterprise,

           sizeof(objid_enterprise));

        pdu->enterprise_length =

        sizeof(objid_enterprise) / sizeof(oid);

    } else {

        name_length = MAX_OID_LEN;

        if (!snmp_parse_oid(argv[arg], name, &name_length)) {

        snmp_perror(argv[arg]);

        /* usage(); - DUMMY 

        SOCK_CLEANUP;

        exit(1);

        }*/

       /* pdu->enterprise = (oid *) malloc(name_length * sizeof(oid));

        memcpy(pdu->enterprise, name, name_length * sizeof(oid));

        pdu->enterprise_length = name_length;

    }*/



    if (++arg >= argc) {

        fprintf(stderr, "Missing agent parameter\n");

        /* usage(); - DUMMY */

        SOCK_CLEANUP;

        exit(1);

    }

    agent = argv[arg];

    if (agent != NULL && strlen(agent) != 0) {

      //  *pdu_in_addr_t = parse_address(agent);

    } else {

        *pdu_in_addr_t = get_myaddr();

    }

    if (++arg == argc) {

        fprintf(stderr, "Missing generic-trap parameter\n");

        /* usage(); - DUMMY */

        SOCK_CLEANUP;

        exit(1);

    }

    trap = argv[arg];

    pdu->trap_type = atoi(trap);

    if (++arg == argc) {

        fprintf(stderr, "Missing specific-trap parameter\n");

        /* usage(); - DUMMY */

        SOCK_CLEANUP;

        exit(1);

    }

    specific = argv[arg];

    pdu->specific_type = atoi(specific);

    if (++arg == argc) {

        fprintf(stderr, "Missing uptime parameter\n");

        /* usage() - DUMMY */;

        SOCK_CLEANUP;

        exit(1);

    }

    description = argv[arg];

    if (description == NULL || *description == 0)

        pdu->time = get_uptime();

    else

        pdu->time = atol(description);

    } else {

    long        sysuptime;

    char        csysuptime[20];



    pdu = snmp_pdu_create(SNMP_MSG_TRAP2);



    /* trap = argv[arg]; */ /* This is sysuptime */

    /* Always get the sysuptime from system, temporarily set *trap=0 */



    sysuptime = get_uptime();

    sprintf(csysuptime, "%ld", sysuptime);

    trap = csysuptime;



    /*snmp_add_var(pdu, objid_sysuptime,

             sizeof(objid_sysuptime) / sizeof(oid), 't', trap);*/



   /* if (snmp_add_var

        (pdu, objid_snmptrap, sizeof(objid_snmptrap) / sizeof(oid),

         'o', NURI_ENTERPRISE_OID) != 0) {

        

        printf ("***** objid_snmptrap problem...exiting....\n");

        SOCK_CLEANUP;

        exit(1);

    }*/

    }

    memset(name,'\0',APP_MAX_OID_LEN);

    name_length = APP_MAX_OID_LEN;

    for (icnt = 0; icnt < length; icnt++)

    {

        if (!snmp_parse_oid(stTrapPDU[icnt].acVariable, name, &name_length)) {

#ifdef APP_DEBUG

           printf("OID: %s\n",stTrapPDU[icnt].acVariable);

           printf ("****** argument oid problem.................\n");

#endif

           SOCK_CLEANUP;

           exit(1);

        }

        if (snmp_add_var

        (pdu, name, name_length, stTrapPDU[icnt].cType, stTrapPDU[icnt].pcValue) != 0) {

#ifdef APP_DEBUG

           printf ("****** name=%s name_length=%d SNMPTRAP argument type and value problem..............\n", name, name_length);

#endif

           SOCK_CLEANUP;

           exit(1);

        }

    }//for

    status = snmp_send(ss, pdu) == 0;

    if (status) {

    snmp_sess_perror("snmptrap", ss);

    snmp_free_pdu(pdu);

    exitval = 1;

  }



    snmp_close(ss);

    SOCK_CLEANUP;

#ifdef APP_DEBUG

    printf("Finishing sndtrap\n");

#endif

    return exitval;

}



/*****************************************************************************

 * name             :   sppMeteringTable_nmp_input

 * description      :   This is a callback function for sending trap

 * input parameters :

 * output parameters:

 * return type      :   int

 * global variables :

 * calls            :   appMeteringTable_send_snmptrap

 *****************************************************************************/



static int

appMeteringTable_snmp_input(int operation,

       netsnmp_session * session,

       int reqid, netsnmp_pdu *pdu, void *magic)

{

    return 1;

}



/*****************************************************************************

 * name             :   appMeteringTable_Load_Container_From_File

 * description      :   Loads the POP3Table from file to memory context

 * input parameters :

 * output parameters:

 * return type      :   void

 * global variables :

 * calls            :   init_appMeteringTable

 *****************************************************************************/



void appMeteringTable_Load_Container_From_File ()

{

    FILE *fp = NULL;

    int iCnt=0;

    int iIndex=0;

    appMeteringTable_context stReadCtx;

    appMeteringTable_context *pstContext = NULL;



    /* Open the container file and load all POP3Table rows from

       this file during start up. */



    fp = fopen (APP_CONTAINER_FILE, "rb");

    if (fp == (FILE *) NULL)

    {

#ifdef APP_DEBUG

      printf("Load_Container_From_File\n",

                  "CONTAINER_FILE file open failed \n");

#endif

    }//end of fp

    else

    {

	/* Loading the POP3Table rows from file to sub-agent memory */

        while (fread (&stReadCtx, sizeof (stReadCtx), 1, fp) == 1)

        {

            pstContext = SNMP_MALLOC_TYPEDEF (appMeteringTable_context);

            memcpy (pstContext,&stReadCtx, sizeof(appMeteringTable_context));

	   // iIndex=appMeteringTable_extract_index(pstContext,(netsnmp_index *)pstContext->index);

	   // printf("Index value inside context: %d \n",pstContext->appMeteringIndex);



            netsnmp_assert(pstContext->index.oids == NULL);

            if(snmp_clone_mem( (void*)&pstContext->index.oids, &stReadCtx.idx,

                             stReadCtx.index.len * sizeof(oid) )) {

#ifdef APP_DEBUG

                printf("Load_Container_From_File",

                            "snmp_clone_mem failed.\n");

#endif

	        fclose(fp);

                return;

            }//end of snmp_clone_mem



            pstContext->index.len = stReadCtx.index.len;



            iCnt = CONTAINER_INSERT (cb.container, pstContext);

            if (iCnt)

            {

#ifdef APP_DEBUG

                printf("Load_Container_From_File",

                            "ERROR IN CONTAINER_INSERT FUNCION\n");

#endif

            }//end of iCnt

       }//end of while

#ifdef APP_DEBUG

        printf("Load_Container_From_File",

                    "CONTAINER SIZE=%u\n", CONTAINER_SIZE (cb.container));

#endif

        /* Close the file */

        fclose (fp);



    }//else



    return;

}//appMetering_Load_Container_From_File



/*****************************************************************************

 * name             :   appMeteringTable_Search_Index_From_File

 * description      :   Loads the POP3Table from file to memory context

 * input parameters :

 * output parameters:

 * return type      :   void

 * global variables :

 * calls            :   init_appMeteringTable

 *****************************************************************************/



int appMeteringTable_Search_Index_From_File (short iCurrIndex,short *strapCount){

    FILE *fp = NULL;

    int iIndex=0;

    

    short tmpCount =0;

    short sSet=0;

    char tmp[5];

    appMeteringTable_context stReadCtx;

    appMeteringTable_context *pstContext = NULL;

    

    char cAppBinName_OID[APP_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.3.1.15.";

    char cAppReaction_OID[APP_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.3.1.10.";

    char cAppStartTime_OID[APP_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.3.1.8.";

    char cAppEndTime_OID[APP_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.3.1.9.";

    char cAppAlertMsg_OID[APP_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.3.1.16.";
    char cAppRowStatus_OID[APP_MAX_OID_LEN] =".1.3.6.1.4.1.3204.1.3.34.3.1.11.";



    

    /* Open the container file and load all POP3Table rows from

       this file during start up. */



    fp = fopen (APP_CONTAINER_FILE, "rb");

    if (fp == (FILE *) NULL)

    {

#ifdef APP_DEBUG

      printf("Load_Container_From_File\n",

                  "CONTAINER_FILE file open failed \n");

#endif

	  return APP_FAILURE;

    }//end of fp

    else

    {

        /*Search the file for the given index*/

        while (fread (&stReadCtx, sizeof (stReadCtx), 1, fp) == 1)

        {

            memset(tmp,'\0',5);		 

            pstContext = SNMP_MALLOC_TYPEDEF (appMeteringTable_context);

            memcpy (pstContext,&stReadCtx, sizeof(appMeteringTable_context));

#ifdef APP_DEBUG

	        printf("Index value inside context: %d \n",pstContext->appMeteringIndex);

#endif                

            if(pstContext->appMeteringIndex==iCurrIndex){

                  sprintf(tmp,"%d",iCurrIndex);        

                  strcat(cAppBinName_OID,tmp);

                  strcat(cAppReaction_OID,tmp);

                  strcat(cAppStartTime_OID,tmp);

                  strcat(cAppEndTime_OID,tmp);

		  strcat(cAppAlertMsg_OID,tmp);

		  strcat(cAppRowStatus_OID,tmp);

#ifdef APP_DEBUG

                  printf("Reaction id before concat: %s\n",cAppReaction_OID);

		          printf("Bainary Name before concat: %s\n",cAppBinName_OID); 

#endif

		 if(pstContext->appMeteringBinaryName_len !=0){ 

		     memset(stAppTrap_Var[0].acVariable,'\0',APP_MAX_OID_LEN);

		     memcpy(stAppTrap_Var[0].acVariable,cAppBinName_OID,strlen(cAppBinName_OID));

                  

		     stAppTrap_Var[0].cType = 's';

		     memset(stAppTrap_Var[0].pcValue,'\0',APP_MAX_VAR_LEN);

		     memcpy(stAppTrap_Var[0].pcValue,pstContext->appMeteringBinaryName,

				                 (pstContext->appMeteringBinaryName_len));

		 }

		 else

		 {

		   fclose(fp);

	       return APP_FAILURE;

		 }

                 		 

		 if( pstContext->appMeteringStartTime_len !=0){

                    memset(stAppTrap_Var[1].acVariable,'\0',APP_MAX_OID_LEN);

		    memcpy(stAppTrap_Var[1].acVariable,cAppStartTime_OID,strlen(cAppStartTime_OID));

                 

		    stAppTrap_Var[1].cType = 's';

 

                    memset(stAppTrap_Var[1].pcValue,'\0',APP_MAX_VAR_LEN);

		    memcpy(stAppTrap_Var[1].pcValue,pstContext->appMeteringStartTime,

				 (pstContext->appMeteringStartTime_len));

		 }

		 else

		 {

	        fclose(fp);

		    return APP_FAILURE;

		 }



		 if(pstContext->appMeteringEndTime_len != 0){

                    memset(stAppTrap_Var[2].acVariable,'\0',APP_MAX_OID_LEN);

		    memcpy(stAppTrap_Var[2].acVariable,cAppEndTime_OID,

				  strlen(cAppEndTime_OID));

                 

		    stAppTrap_Var[2].cType = 's';



		  

                    memset(stAppTrap_Var[2].pcValue,'\0',APP_MAX_VAR_LEN);

		    memcpy(stAppTrap_Var[2].pcValue,pstContext->appMeteringEndTime,

				  (pstContext->appMeteringEndTime_len));

		 }

		 else

		 {

	            fclose(fp);

                return APP_FAILURE;

		 }

                



          memset(stAppTrap_Var[3].acVariable,'\0',APP_MAX_OID_LEN);

		  memcpy(stAppTrap_Var[3].acVariable,cAppReaction_OID,strlen(cAppReaction_OID));



		  stAppTrap_Var[3].cType = 'i';

#ifdef APP_DEBUG

          printf("Reaction ID: %s\n",stAppTrap_Var[3].acVariable);

#endif

		  memset(stAppTrap_Var[3].pcValue, '\0', APP_MAX_VAR_LEN);

          sprintf (stAppTrap_Var[3].pcValue, "%ld", pstContext->appMeteringReaction);



		  if(pstContext->appMeteringAlertMessage_len !=0){

		     memset(stAppTrap_Var[4].acVariable,'\0',APP_MAX_OID_LEN);

		     memcpy(stAppTrap_Var[4].acVariable,cAppAlertMsg_OID,

				  strlen(cAppAlertMsg_OID));

                 

		     stAppTrap_Var[4].cType = 's';



		  

             memset(stAppTrap_Var[4].pcValue,'\0',APP_MAX_VAR_LEN);

		     memcpy(stAppTrap_Var[4].pcValue,pstContext->appMeteringAlertMessage,

			                      (pstContext->appMeteringAlertMessage_len));

			 *strapCount =5;



		  }

		  else

             *strapCount = 4;



		  if(pstContext->appMeteringStatus==2){

		     memset(stAppTrap_Var[*strapCount].acVariable,'\0',APP_MAX_OID_LEN);

		     memcpy(stAppTrap_Var[*strapCount].acVariable,cAppRowStatus_OID,

				  strlen(cAppRowStatus_OID));

                 

		     stAppTrap_Var[*strapCount].cType = 'i';



		  

                     memset(stAppTrap_Var[*strapCount].pcValue,'\0',APP_MAX_VAR_LEN);

                     sprintf (stAppTrap_Var[*strapCount].pcValue, "%ld", pstContext->appMeteringStatus);

			 *strapCount =(*strapCount)+1;



		  }

                   		      

         fclose(fp);

		 return APP_SUCCESS;  

	    }//end of pstContext		   

        }//end of while



       fclose(fp);

       return APP_FAILURE; 

    }//end of else

}//appMetering_Search_Index_From_File



