/*
 * Note: this file originally auto-generated by mib2c using
 *       : mib2c.array-user.conf,v 5.15.2.1 2003/02/27 05:59:41 rstory Exp $
 *
 * $Id: jobProcessMasterTable.c,v 1.1 2003/12/01 14:16:22 guga Exp $
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial/
 *
 *
 * You can also join the #net-snmp channel on irc.openprojects.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>
#include <time.h>

#include "jobProcessMasterTable.h"

#define JOB_SUCCESS 1
#define JOB_FAILURE 2

static     netsnmp_handler_registration *my_handler = NULL;
static     netsnmp_table_array_callbacks cb;

oid jobProcessMasterTable_oid[] = { jobProcessMasterTable_TABLE_OID };
size_t jobProcessMasterTable_oid_len = OID_LENGTH(jobProcessMasterTable_oid);
stVarBindArgs stTrap_Var[JM_NO_OF_FIELDS];


#ifdef jobProcessMasterTable_IDX2
/************************************************************
 * keep binary tree to find context by name
 */
static int jobProcessMasterTable_cmp( const void *lhs, const void *rhs );
int jobProcessMasterTable_Search_Index_From_File (short iCurrIndex,short *strapCount);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
jobProcessMasterTable_cmp( const void *lhs, const void *rhs )
{
    jobProcessMasterTable_context *context_l =
        (jobProcessMasterTable_context *)lhs;
    jobProcessMasterTable_context *context_r =
        (jobProcessMasterTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 indexes
     */
   // int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "jobProcessMasterTable_compare not implemented! Container order undefined\n" );
    return 0;
#endif
    
    /*
     * EXAMPLE:
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName);
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
jobProcessMasterTable_context *
jobProcessMasterTable_get( const char *name, int len )
{
    //jobProcessMasterTable_context tmp;

    /** we should have a secondary index */
    netsnmp_assert(cb.container->next != NULL);
    
    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "jobProcessMasterTable_get not implemented!\n" );
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif


/************************************************************
 * Initializes the jobProcessMasterTable module
 */
void
init_jobProcessMasterTable(void)
{
    initialize_table_jobProcessMasterTable();

    /*
     * TODO: perform any startup stuff here
     */
   jobProcessMasterTable_Load_Container_From_File ();


}

/************************************************************
 * the *_row_copy routine
 */
static int jobProcessMasterTable_row_copy(jobProcessMasterTable_context * dst,
                         jobProcessMasterTable_context * src)
{
    if(!dst||!src)
        return 1;
        
    /*
     * copy index, if provided
     */
    if(dst->index.oids)
        free(dst->index.oids);
    if(snmp_clone_mem( (void*)&dst->index.oids, src->index.oids,
                           src->index.len * sizeof(oid) )) {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    

    /*
     * copy components into the context structure
     */
    dst->jobProcessMasterIndex = src->jobProcessMasterIndex;

    memcpy( dst->jobProcessMasterID, src->jobProcessMasterID, src->jobProcessMasterID_len );
    dst->jobProcessMasterID_len = src->jobProcessMasterID_len;

    memcpy( dst->jobProcessMasterName, src->jobProcessMasterName, src->jobProcessMasterName_len );
    dst->jobProcessMasterName_len = src->jobProcessMasterName_len;

    memcpy( dst->jobProcessMasterDescription, src->jobProcessMasterDescription, src->jobProcessMasterDescription_len );
    dst->jobProcessMasterDescription_len = src->jobProcessMasterDescription_len;

    memcpy( dst->jobProcessMasterCreatedDate, src->jobProcessMasterCreatedDate, src->jobProcessMasterCreatedDate_len );
    dst->jobProcessMasterCreatedDate_len = src->jobProcessMasterCreatedDate_len;

    memcpy( dst->jobProcessMasterCreatedUserID, src->jobProcessMasterCreatedUserID, src->jobProcessMasterCreatedUserID_len );
    dst->jobProcessMasterCreatedUserID_len = src->jobProcessMasterCreatedUserID_len;

    memcpy( dst->jobProcessMasterCreatedUserName, src->jobProcessMasterCreatedUserName, src->jobProcessMasterCreatedUserName_len );
    dst->jobProcessMasterCreatedUserName_len = src->jobProcessMasterCreatedUserName_len;

    dst->jobProcessMasterPeriodicInterval = src->jobProcessMasterPeriodicInterval;

    memcpy( dst->jobProcessMasterStartTime, src->jobProcessMasterStartTime, src->jobProcessMasterStartTime_len );
    dst->jobProcessMasterStartTime_len = src->jobProcessMasterStartTime_len;

    memcpy( dst->jobProcessMasterFinishTime, src->jobProcessMasterFinishTime, src->jobProcessMasterFinishTime_len );
    dst->jobProcessMasterFinishTime_len = src->jobProcessMasterFinishTime_len;

    dst->jobProcessMasterCPUPercentUsage = src->jobProcessMasterCPUPercentUsage;

    dst->jobProcessMasterMemoryPercentUsage = src->jobProcessMasterMemoryPercentUsage;

    dst->jobProcessMasterStatus = src->jobProcessMasterStatus;

    memcpy( dst->jobProcessMasterLastUpdatedDateAndTime, src->jobProcessMasterLastUpdatedDateAndTime, src->jobProcessMasterLastUpdatedDateAndTime_len );
    dst->jobProcessMasterLastUpdatedDateAndTime_len = src->jobProcessMasterLastUpdatedDateAndTime_len;

    return 0;
}

#ifdef jobProcessMasterTable_SET_HANDLING

/*
 * the *_extract_index routine
 */
int
jobProcessMasterTable_extract_index( jobProcessMasterTable_context * ctx, netsnmp_index * hdr )
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_jobProcessMasterIndex;
    int err;

    /*
     * copy index, if provided
     */
    if(hdr) {
        netsnmp_assert(ctx->index.oids == NULL);
        if(snmp_clone_mem( (void*)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid) )) {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /**
     * Create variable to hold each component of the index
     */
       memset( &var_jobProcessMasterIndex, 0x00, sizeof(var_jobProcessMasterIndex) );
       var_jobProcessMasterIndex.type = ASN_UNSIGNED;
       /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "jobProcessMasterTable_extract_index index list not implemented!\n" );
    return 0;
#else
      /* var_jobProcessMasterIndex.next_variable = &var_XX;*/
#endif


    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes( hdr->oids, hdr->len, &var_jobProcessMasterIndex );
    if (err == SNMP_ERR_NOERROR) {
       /*
        * copy components into the context structure
        */
                ctx->jobProcessMasterIndex = *var_jobProcessMasterIndex.val.integer;
   
   
           /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_jobProcessMasterIndex.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_jobProcessMasterIndex );

    return err;
}

/************************************************************
 * the *_can_activate routine is called
 * when a row is changed to determine if all the values
 * set are consistent with the row's rules for a row status
 * of ACTIVE.
 *
 * return 1 if the row could be ACTIVE
 * return 0 if the row is not ready for the ACTIVE state
 */
int jobProcessMasterTable_can_activate(jobProcessMasterTable_context *undo_ctx,
                      jobProcessMasterTable_context *row_ctx,
                      netsnmp_request_group * rg)
{
    /*
     * TODO: check for activation requirements here
     */
    return 1;
}

/************************************************************
 * the *_can_deactivate routine is called when a row that is
 * currently ACTIVE is set to a state other than ACTIVE. If
 * there are conditions in which a row should not be allowed
 * to transition out of the ACTIVE state (such as the row being
 * referred to by another row or table), check for them here.
 *
 * return 1 if the row can be set to a non-ACTIVE state
 * return 0 if the row must remain in the ACTIVE state
 */
int jobProcessMasterTable_can_deactivate(jobProcessMasterTable_context *undo_ctx,
                        jobProcessMasterTable_context *row_ctx,
                        netsnmp_request_group * rg)
{
    /*
     * TODO: check for deactivation requirements here
     */
    return 1;
}

/************************************************************
 * the *_can_delete routine is called to determine if a row
 * can be deleted.
 *
 * return 1 if the row can be deleted
 * return 0 if the row cannot be deleted
 */
int jobProcessMasterTable_can_delete(jobProcessMasterTable_context *undo_ctx,
                    jobProcessMasterTable_context *row_ctx,
                    netsnmp_request_group * rg)
{
    /*
     * probably shouldn't delete a row that we can't
     * deactivate.
     */
    if(jobProcessMasterTable_can_deactivate(undo_ctx,row_ctx,rg) != 1)
        return 0;
    
    /*
     * TODO: check for other deletion requirements here
     */
    return 1;
}

#ifdef jobProcessMasterTable_ROW_CREATION
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated jobProcessMasterTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
jobProcessMasterTable_context *
jobProcessMasterTable_create_row( netsnmp_index* hdr)
{
    jobProcessMasterTable_context * ctx =
        SNMP_MALLOC_TYPEDEF(jobProcessMasterTable_context);
    if(!ctx)
        return NULL;
        
    /*
     * TODO: check indexes, if necessary.
     */
    if(jobProcessMasterTable_extract_index( ctx, hdr )) {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }

    /* netsnmp_mutex_init(ctx->lock);
       netsnmp_mutex_lock(ctx->lock); */

    /*
     * TODO: initialize any default values here. This is also
     * first place you really should allocate any memory for
     * yourself to use.  If you allocated memory earlier,
     * make sure you free it for earlier error cases!
     */
    /**
     ctx->jobProcessMasterID = 0;
     ctx->jobProcessMasterName = 0;
     ctx->jobProcessMasterDescription = 0;
     ctx->jobProcessMasterCreatedDate = 0;
     ctx->jobProcessMasterCreatedUserID = 0;
     ctx->jobProcessMasterCreatedUserName = 0;
     ctx->jobProcessMasterPeriodicInterval = 0;
     ctx->jobProcessMasterStartTime = 0;
     ctx->jobProcessMasterFinishTime = 0;
     ctx->jobProcessMasterCPUPercentUsage = 0;
     ctx->jobProcessMasterMemoryPercentUsage = 0;
     ctx->jobProcessMasterStatus = 0;
     ctx->jobProcessMasterLastUpdatedDateAndTime = 0;
    */

    return ctx;
}
#endif

/************************************************************
 * the *_duplicate row routine
 */
jobProcessMasterTable_context *
jobProcessMasterTable_duplicate_row( jobProcessMasterTable_context * row_ctx)
{
    jobProcessMasterTable_context * dup;

    if(!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(jobProcessMasterTable_context);
    if(!dup)
        return NULL;
        
    if(jobProcessMasterTable_row_copy(dup,row_ctx)) {
        free(dup);
        dup = NULL;
    }

    return dup;
}

/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index * jobProcessMasterTable_delete_row( jobProcessMasterTable_context * ctx )
{
  /* netsnmp_mutex_destroy(ctx->lock); */

    if(ctx->index.oids)
        free(ctx->index.oids);

    /*
     * TODO: release any memory you allocated here...
     */

    /*
     * release header
     */
    free( ctx );

    return NULL;
}


/************************************************************
 * RESERVE is used to check the syntax of all the variables
 * provided, that the values being set are sensible and consistent,
 * and to allocate any resources required for performing the SET.
 * After this stage, the expectation is that the set ought to
 * succeed, though this is not guaranteed. (In fact, with the UCD
 * agent, this is done in two passes - RESERVE1, and
 * RESERVE2, to allow for dependancies between variables).
 *
 * BEFORE calling this routine, the agent will call duplicate_row
 * to create a copy of the row (unless this is a new row; i.e.
 * row_created == 1).
 *
 * next state -> SET_RESERVE2 || SET_FREE
 */
void jobProcessMasterTable_set_reserve1( netsnmp_request_group *rg )
{

    jobProcessMasterTable_context *row_ctx =
            (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx =
            (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_variable_list *var;
    netsnmp_request_group_item *current;
    int rc;



    //printf("Inside Set_Reserve1\n");

     
    /*
     * TODO: loop through columns, check syntax and lengths. For
     * columns which have no dependencies, you could also move
     * the value/range checking here to attempt to catch error
     * cases as early as possible.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                                //row_ctx->jobProcessMasterID).len
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterName)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterDescription)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterCreatedDate)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterCreatedUserID)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterCreatedUserName)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->jobProcessMasterPeriodicInterval));
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterStartTime)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterFinishTime)
var->val_len);
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->jobProcessMasterCPUPercentUsage));
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->jobProcessMasterMemoryPercentUsage));
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->jobProcessMasterStatus));
        break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->jobProcessMasterLastUpdatedDateAndTime)
                                                        var->val_len);
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column in "
                     "jobProcessMasterTable_set_reserve1\n");
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc );
        rg->status = SNMP_MAX( rg->status, current->ri->status );
    }


    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

void jobProcessMasterTable_set_reserve2( netsnmp_request_group *rg )
{
    jobProcessMasterTable_context *row_ctx = (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx = (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    netsnmp_variable_list *var;
    int rc;

    rg->rg_void = rg->list->ri;

    /*
     * TODO: loop through columns, check for valid
     * values and any range constraints.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
                rc = netsnmp_check_vb_rowstatus(current->ri->requestvb,
                                                undo_ctx ?
                                                undo_ctx->jobProcessMasterStatus:0);
                rg->rg_void = current->ri;
        break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * Assuming that the RESERVE phases were successful, the next
 * stage is indicated by the action value ACTION. This is used
 * to actually implement the set operation. However, this must
 * either be done into temporary (persistent) storage, or the
 * previous value stored similarly, in case any of the subsequent
 * ACTION calls fail.
 *
 * In your case, changes should be made to row_ctx. A copy of
 * the original row is in undo_ctx.
 */
void jobProcessMasterTable_set_action( netsnmp_request_group *rg )
{

  
    time_t stTime;	
    netsnmp_variable_list *var;
    jobProcessMasterTable_context *row_ctx = (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx = (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    short iIntervalFlg =0;

    int            row_err = 0;
       
       /*Get Updated Date and Time*/
        memset(row_ctx->jobProcessMasterLastUpdatedDateAndTime,'\0',JM_MAX_DT_LEN);

         row_ctx->jobProcessMasterLastUpdatedDateAndTime_len = JM_MAX_DT_LEN;

	 (void *) time(&stTime);

	 strcpy(row_ctx->jobProcessMasterLastUpdatedDateAndTime, (u_char *) date_n_time(&stTime,
				  (size_t *)&(row_ctx->jobProcessMasterLastUpdatedDateAndTime_len)));
  


    /*
     * TODO: loop through columns, copy varbind values
     * to context structure for the row.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterID,var->val.string,var->val_len);
            row_ctx->jobProcessMasterID_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterName,var->val.string,var->val_len);
            row_ctx->jobProcessMasterName_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterDescription,var->val.string,var->val_len);
            row_ctx->jobProcessMasterDescription_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterCreatedDate,var->val.string,var->val_len);
            row_ctx->jobProcessMasterCreatedDate_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterCreatedUserID,var->val.string,var->val_len);
            row_ctx->jobProcessMasterCreatedUserID_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterCreatedUserName,var->val.string,var->val_len);
            row_ctx->jobProcessMasterCreatedUserName_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
            row_ctx->jobProcessMasterPeriodicInterval = *var->val.integer;
	    iIntervalFlg=1;
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterStartTime,var->val.string,var->val_len);
            row_ctx->jobProcessMasterStartTime_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
            memcpy(row_ctx->jobProcessMasterFinishTime,var->val.string,var->val_len);
            row_ctx->jobProcessMasterFinishTime_len = var->val_len;
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            row_ctx->jobProcessMasterCPUPercentUsage = *var->val.integer;
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            row_ctx->jobProcessMasterMemoryPercentUsage = *var->val.integer;
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
            row_ctx->jobProcessMasterStatus = *var->val.integer;
        break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:

	  //printf("Inside SetAction-Date and Time\n");
           	
            memcpy(row_ctx->jobProcessMasterLastUpdatedDateAndTime,var->val.string,var->val_len);
            row_ctx->jobProcessMasterLastUpdatedDateAndTime_len = var->val_len;
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
#ifndef jobProcessMasterTable_CAN_MODIFY_ACTIVE_ROW
    if( undo_ctx && RS_IS_ACTIVE(undo_ctx->jobProcessMasterStatus) &&
        row_ctx && RS_IS_ACTIVE(row_ctx->jobProcessMasterStatus) ) {
            row_err = 1;
    }
#endif

    /*
     * check activation/deactivation
     */
    row_err = netsnmp_table_array_check_row_status(&cb, rg,
                                  row_ctx ? &row_ctx->jobProcessMasterStatus : NULL,
                                  undo_ctx ? &undo_ctx->jobProcessMasterStatus : NULL);
    if(row_err) {
        netsnmp_set_mode_request_error(MODE_SET_BEGIN,
                                       (netsnmp_request_info*)rg->rg_void,
                                       row_err);
        return;
    }

    if((row_ctx->jobProcessMasterStartTime_len==0 ||
	row_ctx->jobProcessMasterFinishTime_len==0 ||
        row_ctx->jobProcessMasterID_len==0) &&
	(row_ctx->jobProcessMasterStatus==4 ||
	 row_ctx->jobProcessMasterStatus==1)) {
	     //printf("Inside if of set-action\n");	
	     row_err = 1;
   }//end of if
   if(row_err) {
        netsnmp_set_mode_request_error(MODE_SET_BEGIN,
                                     rg->list->ri ,
                                       row_err);
        return;
    }//end of if



    /*
     * TODO: if you have dependencies on other tables, this would be
     * a good place to check those, too.
     */
}

/************************************************************
 * Only once the ACTION phase has completed successfully, can
 * the final COMMIT phase be run. This is used to complete any
 * writes that were done into temporary storage, and then release
 * any allocated resources. Note that all the code in this phase
 * should be "safe" code that cannot possibly fail (cue
 * hysterical laughter). The whole intent of the ACTION/COMMIT
 * division is that all of the fallible code should be done in
 * the ACTION phase, so that it can be backed out if necessary.
 *
 * BEFORE calling this routine, the agent will update the
 * container (inserting a row if row_created == 1, or removing
 * the row if row_deleted == 1).
 *
 * AFTER calling this routine, the agent will delete the
 * undo_info.
 */
void jobProcessMasterTable_set_commit( netsnmp_request_group *rg )
{
    FILE *fp=NULL;
    stVarBindArgs stargs[JM_NO_OF_FIELDS];
    char acstrTmpOID[JM_MAX_VAR_LEN];
    int icnt;
    int CPUorMEMFlg=0;
    short srecCount = 0;
    short sRowStatus=0;
    short sSet=0;
    short sAction = 0;
    short strapCount = 0;
    short tmpCount;
    short subcnt;
    short iIndex;
    short srowStatusFlag = 0;
	time_t now;
	
    netsnmp_variable_list *var;
    jobProcessMasterTable_context *ctx =  NULL;
    jobProcessMasterTable_context *row_ctx = (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx = (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;


  	if ( strlen(row_ctx->jobProcessMasterCreatedDate) == 0 )
	{
		// Get the Date-Time in time_t format
		// and update the created time for the newly
		// created row
		(void *) time(&now);
		strcpy(row_ctx->jobProcessMasterCreatedDate,
		(u_char *) date_n_time(&now,
		(size_t*)&(row_ctx->jobProcessMasterCreatedDate_len)));
	}


	
	/*Load the Record in a File*/
    
   fp = fopen (JM_CONTAINER_FILE, "wb");
   if (fp == (FILE *) NULL)
   {
       //printf("JobMasterTable_set_commit",                   "Couldn't open CONTAINER_FILE\n");
        return;
   }//end of if
   ctx = CONTAINER_FIRST(cb.container);
   if (ctx)
   {
        /* Assign ctx index->oids to idx */
        ctx->idx = (unsigned long) *ctx->index.oids;

       if (fwrite (ctx, sizeof (jobProcessMasterTable_context), 1, fp) != 1)
       {
           //printf("JobMasterTable_set_commit",                       "1 write ctx error\n");
	   fclose(fp);
           return;
       }//end of if (fwrite)
    }//end of if (ctx)

    while (ctx)
    {
        ctx = CONTAINER_NEXT(cb.container,ctx);
        if(ctx)
        {
            /* Assign ctx index->oids to idx */
            ctx->idx = (unsigned long) *ctx->index.oids;

            if (fwrite (ctx, sizeof (jobProcessMasterTable_context), 1, fp) != 1)
            {
               //printf("JobMasterTable_set_commit",                           "2 write ctx error \n");
	       fclose(fp);
               return;
            }//end of if (fwrite)
        }//end of if (ctx)
    }//end of while (ctx)

    fclose (fp);


    
    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        //strcpy(acstrTmpOID,"");
	memset(acstrTmpOID,'\0',JM_MAX_VAR_LEN);
        memset(stargs[srecCount].acVariable,0,sizeof(stargs[srecCount].acVariable));
        for(icnt=0;icnt<var->name_length;icnt++)
        {
          sprintf(acstrTmpOID, ".%lu",var->name[icnt]);
          strcat (stargs[srecCount].acVariable,acstrTmpOID);
        }//for icnt

	sprintf(acstrTmpOID,"%lu",var->name[(var->name_length-1)]);
	iIndex = atoi(acstrTmpOID);
	//printf("Index value is %d\n",iIndex);

        //printf("Variable: %s\n",stargs[srecCount].acVariable);

        //printf("Action before assigning: %d\n",sAction);
        switch ((short) var->type)
        {
         case ASN_INTEGER:
           stargs[srecCount].cType='i';
           //printf("Type is integer : %d\n",(short) var->type);
           //printf("Value: %d\n",*(var->val.integer));
           memset (stargs[srecCount].pcValue, '\0', sizeof (stargs[srecCount].pcValue));
           sprintf (stargs[srecCount].pcValue, "%ld",  *(var->val.integer));
           //printf("****** After copying args[%d].pcValue=%s\n",                    srecCount, stargs[srecCount].pcValue);
          break;

         case ASN_OCTET_STR:
           stargs[srecCount].cType='s';
           //printf("Type is an OCTET string\n");
           //printf("%d\n",(short) var->type);
           //printf("Value: %s\n",var->val.string);
           memset (stargs[srecCount].pcValue,'\0',sizeof (stargs[srecCount].pcValue));
           memcpy (stargs[srecCount].pcValue, var->val.string,var->val_len);
           //printf("Value after copying: %s\n",stargs[srecCount].pcValue);
           break;

        default:
          //printf ("WARNING: TYPE NOT HANDLED....\n");
        break;
     }//switch         
        
    
    switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
	    /** DisplayString = ASN_OCTET_STR */
            sSet++;
            //printf("Inside masterID: %d\n",sSet);	    
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
	    sSet++;
            //printf("Inside periodic interval: %d\n",sSet);	
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
	     //printf("Inside start time: %d\n",sSet);	
	    sSet++; 
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
	     //printf("Inside finish Time: %d\n",sSet);	
	    sSet++;
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
             CPUorMEMFlg=1;
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
             CPUorMEMFlg=1;
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
	     //printf("ROwstatus\n");
             sRowStatus = atoi(stargs[srecCount].pcValue);
    
	   break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
     srecCount++; 

    }
   
    /*Check if user is modifying the cpu utilization or memory utilization*/
     if(CPUorMEMFlg==1)
     {
         //printf("No need to send TRAP and Returning\n");     
         return;
     }
  
       /*Send Trap only when the mandatory fields are set*/
        switch (sRowStatus){
	   case JM_ROW_CREATE:
               if (sSet==4){
                   //printf("Inside Sending Trap\n");
		   sAction = TRAP; 
               }//if
	       break;
	    case JM_ROW_DELETE:
	       //printf("Inside Delete\n");
	        sAction = TRAP;
	        break;
		
	    default:
	       //printf("Inside Modify value of index: %d\n",iIndex);
		     tmpCount = srecCount;  
	             if(jobProcessMasterTable_Search_Index_From_File (iIndex,&strapCount) == JOB_SUCCESS)
	             {
		      //printf("Inside JobSuccess in set_commit-modify\n");	     
                      for(icnt = 0;icnt<strapCount;icnt++)
		      {
		       	for(subcnt =0;subcnt<tmpCount;subcnt++)
			{
			 if (strcmp(stTrap_Var[icnt].acVariable,stargs[subcnt].acVariable)==0){
			   break;
		         }
			}//end of for subcnt
		       if(subcnt == tmpCount){	
	                memset (stargs[srecCount].acVariable,'\0',JM_MAX_OID_LEN);
                        memcpy (stargs[srecCount].acVariable,stTrap_Var[icnt].acVariable,
				       strlen(stTrap_Var[icnt].acVariable));
			//printf("Size of stargs: %d\n",strlen(stargs[srecCount].acVariable));
	//		printf("Size of trap: %d\n",strlen(stTrap_Var[icnt].acVariable));
		
                        stargs[srecCount].cType = stTrap_Var[icnt].cType;
			
		        memset (stargs[srecCount].pcValue,'\0',JM_MAX_VAR_LEN);
                        memcpy (stargs[srecCount].pcValue,stTrap_Var[icnt].pcValue,
		      		       strlen(stTrap_Var[icnt].pcValue));
			srecCount++;
		       }//end of if
		     }//end of for icnt
	                               		 
                    sAction = TRAP;
	          }//end of check      
			     
	       break;
	}//switch
        //printf("Action: %d\n",sAction);
	//printf("RowStatus: %d\n",sRowStatus);
	//printf("set: %d\n",sSet);
        if(sAction == TRAP){
           //printf("Inside sAction\n");		
	   jobProcessMasterTable_send_snmptrap(srecCount,stargs,2501);
	}
 
    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If either of the RESERVE calls fail, the write routines
 * are called again with the FREE action, to release any resources
 * that have been allocated. The agent will then return a failure
 * response to the requesting application.
 *
 * AFTER calling this routine, the agent will delete undo_info.
 */
void jobProcessMasterTable_set_free( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    jobProcessMasterTable_context *row_ctx = (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx = (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        default: /** We shouldn't get here */
            /** should have been logged in reserve1 */
        break;
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If the ACTION phase does fail (for example due to an apparently
 * valid, but unacceptable value, or an unforeseen problem), then
 * the list of write routines are called again, with the UNDO
 * action. This requires the routine to reset the value that was
 * changed to its previous value (assuming it was actually changed),
 * and then to release any resources that had been allocated. As
 * with the FREE phase, the agent will then return an indication
 * of the error to the requesting application.
 *
 * BEFORE calling this routine, the agent will update the container
 * (remove any newly inserted row, re-insert any removed row).
 *
 * AFTER calling this routing, the agent will call row_copy
 * to restore the data in existing_row from the date in undo_info.
 * Then undo_info will be deleted (or existing row, if row_created
 * == 1).
 */
void jobProcessMasterTable_set_undo( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    jobProcessMasterTable_context *row_ctx = (jobProcessMasterTable_context *)rg->existing_row;
    jobProcessMasterTable_context *undo_ctx = (jobProcessMasterTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
        break;

        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

#endif /** jobProcessMasterTable_SET_HANDLING */


/************************************************************
 *
 * Initialize the jobProcessMasterTable table by defining its contents and how it's structured
 */
void
initialize_table_jobProcessMasterTable(void)
{
    netsnmp_table_registration_info *table_info;

    if(my_handler) {
        snmp_log(LOG_ERR, "initialize_table_jobProcessMasterTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    /* if your table is read only, it's easiest to change the
       HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY */
    my_handler = netsnmp_create_handler_registration("jobProcessMasterTable",
                                             netsnmp_table_array_helper_handler,
                                             jobProcessMasterTable_oid,
                                             jobProcessMasterTable_oid_len,
                                             HANDLER_CAN_RWRITE);
            
    if (!my_handler || !table_info) {
        snmp_log(LOG_ERR, "malloc failed in "
                 "initialize_table_jobProcessMasterTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
        /** index: jobProcessMasterIndex */
        netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = jobProcessMasterTable_COL_MIN;
    table_info->max_column = jobProcessMasterTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = jobProcessMasterTable_get_value;
    cb.container = netsnmp_container_find("jobProcessMasterTable_primary:"
                                          "jobProcessMasterTable:"
                                          "table_container");
#ifdef jobProcessMasterTable_IDX2
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("jobProcessMasterTable_secondary:"
                                                       "jobProcessMasterTable:"
                                                       "table_container"));
    cb.container->next->compare = jobProcessMasterTable_cmp;
#endif
#ifdef jobProcessMasterTable_SET_HANDLING
    cb.can_set = 1;
#ifdef jobProcessMasterTable_ROW_CREATION
    cb.create_row = (UserRowMethod*)jobProcessMasterTable_create_row;
#endif
    cb.duplicate_row = (UserRowMethod*)jobProcessMasterTable_duplicate_row;
    cb.delete_row = (UserRowMethod*)jobProcessMasterTable_delete_row;
    cb.row_copy = (Netsnmp_User_Row_Operation *)jobProcessMasterTable_row_copy;

    cb.can_activate = (Netsnmp_User_Row_Action *)jobProcessMasterTable_can_activate;
    cb.can_deactivate = (Netsnmp_User_Row_Action *)jobProcessMasterTable_can_deactivate;
    cb.can_delete = (Netsnmp_User_Row_Action *)jobProcessMasterTable_can_delete;

    cb.set_reserve1 = jobProcessMasterTable_set_reserve1;
    cb.set_reserve2 = jobProcessMasterTable_set_reserve2;
    cb.set_action = jobProcessMasterTable_set_action;
    cb.set_commit = jobProcessMasterTable_set_commit;
    cb.set_free = jobProcessMasterTable_set_free;
    cb.set_undo = jobProcessMasterTable_set_undo;
#endif
    DEBUGMSGTL(("initialize_table_jobProcessMasterTable",
                "Registering table jobProcessMasterTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * jobProcessMasterTable_get_value
 */
int jobProcessMasterTable_get_value(
            netsnmp_request_info *request,
            netsnmp_index *item,
            netsnmp_table_request_info *table_info )
{
    netsnmp_variable_list *var = request->requestvb;
    jobProcessMasterTable_context *context = (jobProcessMasterTable_context *)item;

    switch(table_info->colnum) {

        case COLUMN_JOBPROCESSMASTERINDEX:
            /** UNSIGNED32 = ASN_UNSIGNED */
            snmp_set_var_typed_value(var, ASN_UNSIGNED,
                         (char*)&context->jobProcessMasterIndex,
                         sizeof(context->jobProcessMasterIndex) );
        break;
    
        case COLUMN_JOBPROCESSMASTERID:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterID,
                         context->jobProcessMasterID_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERNAME:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterName,
                         context->jobProcessMasterName_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERDESCRIPTION:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterDescription,
                         context->jobProcessMasterDescription_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERCREATEDDATE:
            /** DateAndTime = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterCreatedDate,
                         context->jobProcessMasterCreatedDate_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERCREATEDUSERID:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterCreatedUserID,
                         context->jobProcessMasterCreatedUserID_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERCREATEDUSERNAME:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterCreatedUserName,
                         context->jobProcessMasterCreatedUserName_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERPERIODICINTERVAL:
            /** INTEGER = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->jobProcessMasterPeriodicInterval,
                         sizeof(context->jobProcessMasterPeriodicInterval) );
        break;
    
        case COLUMN_JOBPROCESSMASTERSTARTTIME:
            /** DateAndTime = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterStartTime,
                         context->jobProcessMasterStartTime_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERFINISHTIME:
            /** DateAndTime = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterFinishTime,
                         context->jobProcessMasterFinishTime_len );
        break;
    
        case COLUMN_JOBPROCESSMASTERCPUPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->jobProcessMasterCPUPercentUsage,
                         sizeof(context->jobProcessMasterCPUPercentUsage) );
        break;
    
        case COLUMN_JOBPROCESSMASTERMEMORYPERCENTUSAGE:
            /** INTEGER = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->jobProcessMasterMemoryPercentUsage,
                         sizeof(context->jobProcessMasterMemoryPercentUsage) );
        break;
    
        case COLUMN_JOBPROCESSMASTERSTATUS:
            /** RowStatus = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->jobProcessMasterStatus,
                         sizeof(context->jobProcessMasterStatus) );
        break;
    
        case COLUMN_JOBPROCESSMASTERLASTUPDATEDDATEANDTIME:
            /** DateAndTime = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->jobProcessMasterLastUpdatedDateAndTime,
                         context->jobProcessMasterLastUpdatedDateAndTime_len );
        break;
    
    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                 "jobProcessMasterTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * jobProcessMasterTable_get_by_idx
 */
const jobProcessMasterTable_context *
jobProcessMasterTable_get_by_idx(netsnmp_index * hdr)
{
    return (const jobProcessMasterTable_context *)
        CONTAINER_FIND(cb.container, hdr );
}

int jobProcessMasterTable_send_snmptrap (int length, stVarBindArgs *stTrapPDU, int port)
{
    netsnmp_session session, *ss;
    netsnmp_pdu       *pdu;
    in_addr_t       *pdu_in_addr_t;
    oid            name[JM_MAX_OID_LEN];
    size_t         name_length;
    int            arg = 0;
    int            status;
    char       *trap = NULL, *specific = NULL, *description =
    NULL, *agent = NULL;
    
    int            exitval = 0;
    int            icnt = 0;
    char**        argv = NULL;
    int            argc = 0;
    
   //printf("trapPDU var=%s type=%c val=%s\n", stTrapPDU[0].acVariable,             stTrapPDU[0].cType, stTrapPDU[0].pcValue);

    /** initialize session to default values*/
     
    snmp_sess_init (&session);


    /* Initialize session values - DUMMY */
    session.version = SNMP_VERSION_2c;
    session.timeout = 1 * 1000000L;
    session.retries = 3;
    session.community = (unsigned char *) "public";
    session.community_len = strlen (session.community);

     
    session.peername = "localhost";

    /*DEBUGMSGTL(("send_snmptrap", "trapIP=%lu peername=%s trapPort=%ld\n",
                ctx->trapDestinationIP, session.peername, ctx->trapPort));*/

    SOCK_STARTUP;

    session.callback = jobProcessMasterTable_snmp_input;
    session.callback_magic = NULL;

    
    netsnmp_ds_set_int(NETSNMP_DS_LIBRARY_ID, NETSNMP_DS_LIB_DEFAULT_PORT,
               (int) port);

    if (session.version == SNMP_VERSION_3) {
    /*
     * for traps, we use ourselves as the authoritative engine
     * which is really stupid since command line apps don't have a
     * notion of a persistent engine.  Hence, our boots and time
     * values are probably always really wacked with respect to what
     * a manager would like to see.
     *
     * The following should be enough to:
     *
     * 1) prevent the library from doing discovery for engineid & time.
     * 2) use our engineid instead of the remote engineid for
     * authoritative & privacy related operations.
     * 3) The remote engine must be configured with users for our engineID.
     *
     * -- Wes
     */

    /*
     * setup the engineID based on IP addr.     Need a different
     * algorthim here.  This will cause problems with agents on the
     * same machine sending traps.
     */
    setup_engineID(NULL, NULL);

    /*
     * pick our own engineID
     */
    if (session.securityEngineIDLen == 0 ||
        session.securityEngineID == NULL) {
        session.securityEngineID =
        snmpv3_generate_engineID(&session.securityEngineIDLen);
    }
    if (session.contextEngineIDLen == 0 ||
        session.contextEngineID == NULL) {
        session.contextEngineID =
        snmpv3_generate_engineID(&session.contextEngineIDLen);
    }

    /*
     * set boots and time, which will cause problems if this
     * machine ever reboots and a remote trap receiver has cached our
     * boots and time...  I'll cause a not-in-time-window report to
     * be sent back to this machine.
     */
    if (session.engineBoots == 0)
        session.engineBoots = 1;
    if (session.engineTime == 0)    /* not really correct, */
        session.engineTime = get_uptime();    /* but it'll work. Sort of. */
    }

    ss = snmp_open(&session);
    if (ss == NULL) {
    /*
     * diagnose snmp_open errors with the input netsnmp_session pointer
     */
    snmp_sess_perror("snmptrap", &session);

    SOCK_CLEANUP;
    exit(1);
    }

    if (session.version == SNMP_VERSION_1) {
    pdu = snmp_pdu_create(SNMP_MSG_TRAP);
    pdu_in_addr_t = (in_addr_t *) pdu->agent_addr;

    /*if (argv[arg][0] == 0) {

        pdu->enterprise = (oid *) malloc(sizeof(objid_enterprise));
        memcpy(pdu->enterprise, objid_enterprise,
           sizeof(objid_enterprise));
        pdu->enterprise_length =
        sizeof(objid_enterprise) / sizeof(oid);
    } else {
        name_length = MAX_OID_LEN;
        if (!snmp_parse_oid(argv[arg], name, &name_length)) {
        snmp_perror(argv[arg]);
        /* usage(); - DUMMY 
        SOCK_CLEANUP;
        exit(1);
        }*/
       /* pdu->enterprise = (oid *) malloc(name_length * sizeof(oid));
        memcpy(pdu->enterprise, name, name_length * sizeof(oid));
        pdu->enterprise_length = name_length;
    }*/

    if (++arg >= argc) {
        fprintf(stderr, "Missing agent parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    agent = argv[arg];
    if (agent != NULL && strlen(agent) != 0) {
      //  *pdu_in_addr_t = parse_address(agent);
    } else {
        *pdu_in_addr_t = get_myaddr();
    }
    if (++arg == argc) {
        fprintf(stderr, "Missing generic-trap parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    trap = argv[arg];
    pdu->trap_type = atoi(trap);
    if (++arg == argc) {
        fprintf(stderr, "Missing specific-trap parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    specific = argv[arg];
    pdu->specific_type = atoi(specific);
    if (++arg == argc) {
        fprintf(stderr, "Missing uptime parameter\n");
        /* usage() - DUMMY */;
        SOCK_CLEANUP;
        exit(1);
    }
    description = argv[arg];
    if (description == NULL || *description == 0)
        pdu->time = get_uptime();
    else
        pdu->time = atol(description);
    } else {
    long        sysuptime;
    char        csysuptime[20];

    pdu = snmp_pdu_create(SNMP_MSG_TRAP2);

    /* trap = argv[arg]; */ /* This is sysuptime */
    /* Always get the sysuptime from system, temporarily set *trap=0 */

    sysuptime = get_uptime();
    sprintf(csysuptime, "%ld", sysuptime);
    trap = csysuptime;

    /*snmp_add_var(pdu, objid_sysuptime,
             sizeof(objid_sysuptime) / sizeof(oid), 't', trap);*/

   /* if (snmp_add_var
        (pdu, objid_snmptrap, sizeof(objid_snmptrap) / sizeof(oid),
         'o', NURI_ENTERPRISE_OID) != 0) {
        
        printf ("***** objid_snmptrap problem...exiting....\n");
        SOCK_CLEANUP;
        exit(1);
    }*/
    }
    name_length = JM_MAX_OID_LEN;
    for (icnt = 0; icnt < length; icnt++)
    {
        if (!snmp_parse_oid(stTrapPDU[icnt].acVariable, name, &name_length)) {
           //printf("OID: %s\n",stTrapPDU[icnt].acVariable);
           //printf ("****** argument oid problem.................\n");
           SOCK_CLEANUP;
           exit(1);
        }
        if (snmp_add_var
        (pdu, name, name_length, stTrapPDU[icnt].cType, stTrapPDU[icnt].pcValue) != 0) {
           //printf ("****** name=%s name_length=%d SNMPTRAP argument type and value problem..............\n", name, name_length);
           SOCK_CLEANUP;
           exit(1);
        }
    }//for
    status = snmp_send(ss, pdu) == 0;
    if (status) {
    snmp_sess_perror("snmptrap", ss);
    snmp_free_pdu(pdu);
    exitval = 1;
  }

    snmp_close(ss);
    SOCK_CLEANUP;
    //printf("Finishing sndtrap\n");
    return exitval;
}

/*****************************************************************************
 * name             :   snmp_input
 * description      :   This is a callback function for sending trap
 * input parameters :
 * output parameters:
 * return type      :   int
 * global variables :
 * calls            :   jobProcessMasterTable_send_snmptrap
 *****************************************************************************/

static int
jobProcessMasterTable_snmp_input(int operation,
       netsnmp_session * session,
       int reqid, netsnmp_pdu *pdu, void *magic)
{
    return 1;
}

/*****************************************************************************
 * name             :   jobProcessMasterTable_Load_Container_From_File
 * description      :   Loads the JobMasterTable from file to memory context
 * input parameters :
 * output parameters:
 * return type      :   void
 * global variables :
 * calls            :   init_jobProcessMasterTable
 *****************************************************************************/

void jobProcessMasterTable_Load_Container_From_File ()
{
    FILE *fp = NULL;
    int iCnt=0;
    jobProcessMasterTable_context stReadCtx;
    jobProcessMasterTable_context *pstContext = NULL;

    /* Open the container file and load all JobMasterTable rows from
       this file during start up. */

    fp = fopen (JM_CONTAINER_FILE, "rb");
    if (fp == (FILE *) NULL)
    {
      //printf("Load_Container_From_File",                  "CONTAINER_FILE file open failed \n");
    }//end of fp
    else
    {
	/* Loading the JobMasterTable rows from file to sub-agent memory */
        while (fread (&stReadCtx, sizeof (stReadCtx), 1, fp) == 1)
        {
            pstContext = SNMP_MALLOC_TYPEDEF (jobProcessMasterTable_context);
            memcpy (pstContext,&stReadCtx, sizeof (jobProcessMasterTable_context));

            netsnmp_assert(pstContext->index.oids == NULL);
            if(snmp_clone_mem( (void*)&pstContext->index.oids, &stReadCtx.idx,
                             stReadCtx.index.len * sizeof(oid) )) {
                //printf("Load_Container_From_File",                            "snmp_clone_mem failed.\n");
		fclose(fp);
                return;
            }//end of snmp_clone_mem

            pstContext->index.len = stReadCtx.index.len;

            iCnt = CONTAINER_INSERT (cb.container, pstContext);
            if (iCnt)
            {
                //printf("Load_Container_From_File",                            "ERROR IN CONTAINER_INSERT FUNCION\n");
            }//end of iCnt
       }//end of while

        //printf("Load_Container_From_File",                    "CONTAINER SIZE=%u\n", CONTAINER_SIZE (cb.container));
        /* Close the file */
        fclose (fp);

    }//else

    return;
}//Load_Container_From_File

/*****************************************************************************
 * name             :   jobProcessMasterTable_Search_Index_From_File
 * description      :   Loads the POP3Table from file to memory context
 * input parameters :
 * output parameters:
 * return type      :   void
 * global variables :
 * calls            :   
 *****************************************************************************/

int jobProcessMasterTable_Search_Index_From_File (short iCurrIndex,short *strapCount)
{
    FILE *fp = NULL;
    int iIndex=0;
    short icnt;
    short sSet=0;
    char tmp[5];
    char cjobMasterID_OID[JM_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.1.1.1.2.";
    char cjobMasterStartTime_OID[JM_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.1.1.1.9.";
    char cjobMasterFinishTime_OID[JM_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.1.1.1.10.";
    char cjobMasterInterval_OID[JM_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.1.1.1.8.";

    char cjobMasterRowStatus_OID[JM_MAX_OID_LEN] = ".1.3.6.1.4.1.3204.1.3.34.1.1.1.13.";
    
    jobProcessMasterTable_context stReadCtx;
    jobProcessMasterTable_context *pstContext = NULL;
        
    /* Open the container file and load all POP3Table rows from
       this file during start up. */

    fp = fopen (JM_CONTAINER_FILE, "rb");
    if (fp == (FILE *) NULL)
    {
      //printf("Load_Container_From_File\n",                  "CONTAINER_FILE file open failed \n");
      return JOB_FAILURE;
    }//end of fp
    else
    {
        /*Search the file for the given index*/
        while (fread (&stReadCtx, sizeof (stReadCtx), 1, fp) == 1)
        {
	    memset(tmp,'\0',5);	
            pstContext = SNMP_MALLOC_TYPEDEF (jobProcessMasterTable_context);
            memcpy (pstContext,&stReadCtx, sizeof(jobProcessMasterTable_context));
	    //printf("Index value inside context: %d \n",pstContext->jobProcessMasterIndex);
                
            if(pstContext->jobProcessMasterIndex == iCurrIndex){
		  sprintf(tmp,"%d",iCurrIndex);        
                  strcat(cjobMasterID_OID,tmp);
                  strcat(cjobMasterInterval_OID,tmp);
                  strcat(cjobMasterStartTime_OID,tmp);
                  strcat(cjobMasterFinishTime_OID,tmp);
                  strcat(cjobMasterRowStatus_OID,tmp);
		  if(pstContext->jobProcessMasterID_len != 0){
   
		     memset(stTrap_Var[0].acVariable,'\0',JM_MAX_OID_LEN);
		     memcpy(stTrap_Var[0].acVariable,cjobMasterID_OID,strlen(cjobMasterID_OID));
                  
		     stTrap_Var[0].cType = 's';
		     memset(stTrap_Var[0].pcValue,'\0',JM_MAX_VAR_LEN);
		     memcpy(stTrap_Var[0].pcValue,pstContext->jobProcessMasterID,
				  (pstContext->jobProcessMasterID_len));
		  }//end of if
		  else
		  {
	           fclose(fp);     
		   return JOB_FAILURE;
		  }//end of else
		  
      		  if(pstContext->jobProcessMasterStartTime_len !=0){
		  
                      memset(stTrap_Var[1].acVariable,'\0',JM_MAX_OID_LEN);
		      memcpy(stTrap_Var[1].acVariable,cjobMasterStartTime_OID,strlen(cjobMasterStartTime_OID));
                 
		      stTrap_Var[1].cType = 's';
 
                      memset(stTrap_Var[1].pcValue,'\0',JM_MAX_VAR_LEN);
                      memcpy(stTrap_Var[1].pcValue,pstContext->jobProcessMasterStartTime,
	          			  (pstContext->jobProcessMasterStartTime_len));
		  }//end of if
	          else
		  {
                   fclose(fp);     
		   return JOB_FAILURE;
		  }//end of else

		  if(pstContext->jobProcessMasterFinishTime_len !=0){
   
                     memset(stTrap_Var[2].acVariable,'\0',JM_MAX_OID_LEN);
                     memcpy(stTrap_Var[2].acVariable,cjobMasterFinishTime_OID,
				      strlen(cjobMasterFinishTime_OID));
                 
		     stTrap_Var[2].cType = 's';

		  
                     memset(stTrap_Var[2].pcValue,'\0',JM_MAX_VAR_LEN);
		     memcpy(stTrap_Var[2].pcValue,pstContext->jobProcessMasterFinishTime,
				  (pstContext->jobProcessMasterFinishTime_len));
                  }
		  else
		  {
	            fclose(fp);     
		   return JOB_FAILURE;
		  }//end of else
 
                  memset(stTrap_Var[3].acVariable,'\0',JM_MAX_OID_LEN);
		  memcpy(stTrap_Var[3].acVariable,cjobMasterInterval_OID,strlen(cjobMasterInterval_OID));

		  stTrap_Var[3].cType = 'i';

		  
                  memset(stTrap_Var[3].pcValue, '\0', JM_MAX_VAR_LEN);
                  sprintf (stTrap_Var[3].pcValue, "%ld", pstContext->jobProcessMasterPeriodicInterval);
                if(pstContext->jobProcessMasterStatus ==2){  
                  memset(stTrap_Var[4].acVariable,'\0',JM_MAX_OID_LEN);
		  memcpy(stTrap_Var[4].acVariable,cjobMasterRowStatus_OID,strlen(cjobMasterRowStatus_OID));

		  stTrap_Var[4].cType = 'i';

		  
                  memset(stTrap_Var[4].pcValue, '\0', JM_MAX_VAR_LEN);
                  sprintf (stTrap_Var[4].pcValue, "%ld", pstContext->jobProcessMasterStatus);
                 *strapCount = 5;
}
else
 *strapCount = 4;          
		  //printf("ID Value: %s\n",stTrap_Var[0].pcValue);
		  
                 /*printf("Start Time Value: %s\n",stTrap_Var[1].pcValue);
                 printf("Finish Value: %s\n",stTrap_Var[2].pcValue);
                 printf("Interval Value: %s\n",stTrap_Var[3].pcValue);*/


                 fclose(fp);
		 //printf("Inside if -before success\n");
		 return JOB_SUCCESS;  
             }//end of if
	    //printf("Inside While \n"); 
	   }//end of while
	 fclose(fp);
	 //printf("End of Search\n");
	 return JOB_FAILURE;
	}//end of else
	
}//end of function
