/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */
#ifndef CPUTABLE_H
#define CPUTABLE_H

/* function declarations */
void init_cpuTable(void);
FindVarMethod var_cpuTable;
FindVarMethod var_cpuTable;

typedef struct gstCpu{
	unsigned long ulIdx;
	unsigned long ulUser;
	unsigned long ulNice;
	unsigned long ulSys;
	unsigned long ulIdle;
}gstCpu;

#define CPUINFO_SYMBOL "cpuinfo"
#endif /* CPUTABLE_H */
