/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "fsTable.h"
#include <sys/statfs.h>
#include <sys/stat.h>
#include <mntent.h> 

/* #defines section */
#define HRFS_MONOTONICALLY_INCREASING
#define KBYTE 1024

/* Global Declaration */
/* 
 * fsTable_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid fsTable_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,24 };

/* 
 * variable4 fsTable_variables:
 *   this variable defines function callbacks and type return information 
 *   for the  mib section 
 */

struct variable4 fsTable_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

};

/* Extern Declaration */
extern struct mntent *HRFS_entry;

/* Static Declaration */
static struct statfs gstStatFs;

/*    (L = length of the oidsuffix) */
unsigned long VAR;
#define VALUE 0
#define TABLE_SIZE 6

/** Initializes the fsTable module */
void
init_fsTable(void)
{

    DEBUGMSGTL(("fsTable", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("fsTable", fsTable_variables, variable4,
               fsTable_variables_oid);

    /* place any other initialization junk you need here */
}

