/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "MessageQueue.h"
#include <linux/msg.h>
#include <pwd.h>
#include <grp.h>

#define MSG_MONOTONICALLY_INCREASING
#define MSG_FILE "/proc/sysvipc/msg"
#define CACHE_TIMEOUT 5
#define MICROSEC 1000000

/*
 * MessageQueue_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid MessageQueue_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,29 };

/*
 * variable4 MessageQueue_variables:
 *   this variable defines function callbacks and type return information
 *   for the  mib section
 */

struct variable4 MessageQueue_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

};
/*    (L = length of the oidsuffix) */

struct gstMsg{
	unsigned int  uiKey;
	unsigned long ulMsgId;
	unsigned int  uiPerms;
	unsigned long ulCBytes;
	unsigned long ulQNum;
	unsigned long ulLSPid;
	unsigned long ulLRPid;
	unsigned int  uiUID;
	unsigned int  uiGID;
	unsigned int  uiCUID;
	unsigned int  uiCGID;
	unsigned long ulSTime;
	unsigned long ulRTime;
	unsigned long ulCTime;
};

/* Function prototype */
void msgQTable_GetMsgQ();

/* Global Declaration */
static struct gstMsg *gpstMsgFirst = NULL;
static struct gstMsg *gpstMsgStat = NULL;
static struct timeval gstDCTimeVal={0};
static int giMsgIdx = 0;
static int giMsgCnt = 0;

/** Initializes the MessageQueue module */
void
init_MessageQueue(void)
{

    DEBUGMSGTL(("MessageQueue", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("MessageQueue", MessageQueue_variables, variable4,
               MessageQueue_variables_oid);

    /* place any other initialization junk you need here */
}

/*****************************************************************************
 * name             :   msgQTable_GetMsgQ
 * description      :   
 * input parameters :   None
 * output parameters:   None
 * return type      :   void
 * global variables :   giMsgCnt, gpstMsgFirst
 * calls            :   void
 *****************************************************************************/
void msgQTable_GetMsgQ(){
    
    FILE	*fpMsg = NULL;    
    int         iFirst = 0;
    int iSize = 0;
    char        buff[128];
    struct gstMsg *stMsgCurrent;
    stMsgCurrent = NULL;     
    giMsgCnt = 0; 
        
    if(fpMsg != NULL)
        fclose(fpMsg);
    if ((fpMsg = fopen(MSG_FILE, "r" )) != NULL){
        memset(buff, '\0', 128);
	while (fgets(buff, sizeof(buff), fpMsg) != NULL) {
            if(iFirst == 0){
		iFirst = 1;
		continue;
	    }			

	    iSize = (giMsgCnt + 1) * sizeof (struct gstMsg);
	    stMsgCurrent = (struct gstMsg *) realloc (stMsgCurrent, iSize);
	    sscanf(buff, " %d %lu %d %lu %lu %lu %lu %d %d %d %d %lu %lu %lu ",
				&(stMsgCurrent[giMsgCnt].uiKey), 
				&(stMsgCurrent[giMsgCnt].ulMsgId), 
				&(stMsgCurrent[giMsgCnt].uiPerms), 
				&(stMsgCurrent[giMsgCnt].ulCBytes), 
				&(stMsgCurrent[giMsgCnt].ulQNum), 
				&(stMsgCurrent[giMsgCnt].ulLSPid), 
				&(stMsgCurrent[giMsgCnt].ulLRPid), 
				&(stMsgCurrent[giMsgCnt].uiUID), 
				&(stMsgCurrent[giMsgCnt].uiGID), 
				&(stMsgCurrent[giMsgCnt].uiCUID), 
				&(stMsgCurrent[giMsgCnt].uiCGID), 
				&(stMsgCurrent[giMsgCnt].ulSTime), 
				&(stMsgCurrent[giMsgCnt].ulRTime), 
				&(stMsgCurrent[giMsgCnt].ulCTime));
	    giMsgCnt++;	
            memset(buff, '\0', 128);
	}
	gpstMsgFirst = stMsgCurrent;
        if(fpMsg)
    	    fclose(fpMsg);
    }
    else{
		snmp_log(LOG_ERR,"/proc/sysvipc/msg open error\n");
    }
}



