/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */
#ifndef SEMAPHORE_H
#define SEMAPHORE_H

/* function declarations */
void init_Semaphore(void);
FindVarMethod var_Semaphore;

#endif /* SEMAPHORE_H */
