/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */
#ifndef SWAP_H
#define SWAP_H

/* function declarations */
void init_Swap(void);
FindVarMethod var_Swap;

#endif /* SWAP_H */
