/*****************************************************************************
 *
 * [userAccessControlTable.c]
 *
 *      Copyright (c) 2002 Wipro Technologies
 *      All rights Reserved
 *
 * author:
 *      Name Karthikeyan Subramani
 *
 * description :
 *      [ TO get the user details]
 *
 * TODO:
 *      [ Things to be improved ]
 *
 * CM Details:
 *
 * $Author: karthis $
 * $Log: userAccessControlTable.c,v $
 * Revision 1.3  2004/01/21 07:24:48  karthis
 * fixed crash copied the UAC UGC from hp src
 *
 * Revision 1.4  2004/01/19 06:05:52  vijaysp
 * Added endpwent() in two places to avoid agent crash
 *
 * Revision 1.3  2004/01/06 05:42:09  testteam
 * gmaxuser =0
 *
 * Revision 1.2  2004/01/05 14:57:46  karthis
 * update coding standard
 *
 * Revision 1.4  2004/01/05 14:04:07  karthis
 * update coding standard
 *
 * $State: Exp $  
 * $Id: userAccessControlTable.c,v 1.3 2004/01/21 07:24:48 karthis Exp $
 * $Name: NASCenterAgent_29Jan2004_Patch3_SrcRls $
 ****************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */

/********************************* includes *********************************/
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "userAccessControlTable.h"
#include <pwd.h>
/* 
 * userAccessControlTable_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

/****************************** local macros ********************************
 *
 * (Macros shareable with rest of the modules are present in .h file)
 */

#define USERINDEX_MONOTONICALLY_INCREASING
#define UCACHE_TIME 5 

/********************* local structure/union definitions ********************/
struct user
{ 
  char username[100];
  char password[100]; 
  char uid[100];
  int gid;
  char desc[100];
}userinfo;
struct passwd *pw;
struct timeval gusttDCTimeVal = { 0 };


/********************* prototypes for local functions ***********************/
void useraccessTable_Init();
int useraccessTable_GetNext();
int
header_useraccessTable(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method);
void GetUserData(void);

/************************* Globals within this module ***********************/
int gflag=0;
int guserindex=0; 
int gmaxuser=0;


oid userAccessControlTable_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4};

/* 
 * variable4 userAccessControlTable_variables:
 *   this variable defines function callbacks and type return information 
 *   for the  mib section 
 */

struct variable4 userAccessControlTable_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

};
/*    (L = length of the oidsuffix) */


/** Initializes the userAccessControlTable module */
void
init_userAccessControlTable(void)
{

    DEBUGMSGTL(("userAccessControlTable", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("userAccessControlTable", userAccessControlTable_variables, variable4,
               userAccessControlTable_variables_oid);
    /* place any other initialization junk you need here */
}

/*****************************************************************************
 *
 * name             :   GetUserData
 * description      :   It will intialize the maxusers
 * input parameters :   [void]  - No input Parameters
 * output parameters:   [void] -  No output Parameters
 * return type      :   [void] - No return type
 * global variables :   [gflag=0, gmaxuser] 
 * calls            :   [header_useraccess,init_userAcessControlTable]
 */

void GetUserData(void)
{ 
    DEBUGMSGTL(("userAccessControlTable", "GetUser Called\n"));
    gmaxuser=0;
    gettimeofday(&gusttDCTimeVal, NULL);
    setpwent();
    while(1)
    {  pw=getpwent();
       if (pw==(struct passwd *) NULL)
           break;
       gflag=0; 
       gmaxuser++;
    }
    endpwent();
}
