/*
 * Note: this file originally auto-generated by mib2c using
 *       : mib2c.array-user.conf,v 5.15.2.1 2003/02/27 05:59:41 rstory Exp $
 *
 * $Id: sysStatisticsTable.c,v 1.8 2004/01/07 12:39:28 vijaysp Exp $
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial/
 *
 *
 * You can also join the #net-snmp channel on irc.openprojects.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#ifdef WIN32
#include "../inc/sysStatisticsTable.h"
#include "../../RTCM/inc/trapTable.h"
#else
#include "sysStatisticsTable.h"
#include "trapTable.h"
#endif

static     netsnmp_handler_registration *my_handler = NULL;
netsnmp_table_array_callbacks statcb;

oid sysStatisticsTable_oid[] = { sysStatisticsTable_TABLE_OID };
size_t sysStatisticsTable_oid_len = OID_LENGTH(sysStatisticsTable_oid);

void createSysStatRow(long index, oid *oid, long oidSize);

void destroySysStatRow(long index);

#ifdef sysStatisticsTable_IDX2
/************************************************************
 * keep binary tree to find context by name
 */
static int sysStatisticsTable_cmp( const void *lhs, const void *rhs );

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
sysStatisticsTable_cmp( const void *lhs, const void *rhs )
{
    sysStatisticsTable_context *context_l =
        (sysStatisticsTable_context *)lhs;
    sysStatisticsTable_context *context_r =
        (sysStatisticsTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 indexes
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "sysStatisticsTable_compare not implemented! Container order undefined\n" );
    return 0;
#endif
    
    /*
     * EXAMPLE:
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName);
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
sysStatisticsTable_context *
sysStatisticsTable_get( const char *name, int len )
{
    sysStatisticsTable_context tmp;

    /** we should have a secondary index */
    netsnmp_assert(statcb.container->next != NULL);
    
    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "sysStatisticsTable_get not implemented!\n" );
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(statcb.container->next, &tmp);
     */
}
#endif


/************************************************************
 * Initializes the sysStatisticsTable module
 */
void
init_sysStatisticsTable(void)
{
    initialize_table_sysStatisticsTable();
    /*
     * TODO: perform any startup stuff here
     */
}

/************************************************************
 * the *_row_copy routine
 */
static int sysStatisticsTable_row_copy(sysStatisticsTable_context * dst,
                         sysStatisticsTable_context * src)
{
    if(!dst||!src)
        return 1;
        
    /*
     * copy index, if provided
     */
    if(dst->index.oids)
        free(dst->index.oids);
    if(snmp_clone_mem( (void*)&dst->index.oids, src->index.oids,
                           src->index.len * sizeof(oid) )) {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    

    /*
     * copy components into the context structure
     */
    dst->sysStatisticsIndex = src->sysStatisticsIndex;

    memcpy( dst->sysStatisticsVariable, src->sysStatisticsVariable, src->sysStatisticsVariable_len );
    dst->sysStatisticsVariable_len = src->sysStatisticsVariable_len;

    dst->sysStatisticsPeriod = src->sysStatisticsPeriod;

    dst->sysStatisticsMaxValue = src->sysStatisticsMaxValue;

    dst->sysStatisticsMinValue = src->sysStatisticsMinValue;

    dst->sysStatisticsAvgValue = src->sysStatisticsAvgValue;

    dst->sysStatisticsStd = src->sysStatisticsStd;

    return 0;
}

#ifdef sysStatisticsTable_SET_HANDLING

/*
 * the *_extract_index routine
 */
int
sysStatisticsTable_extract_index( sysStatisticsTable_context * ctx, netsnmp_index * hdr )
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_sysStatisticsIndex;
    int err;

    /*
     * copy index, if provided
     */
    if(hdr) {
        netsnmp_assert(ctx->index.oids == NULL);
        if(snmp_clone_mem( (void*)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid) )) {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /**
     * Create variable to hold each component of the index
     */
       memset( &var_sysStatisticsIndex, 0x00, sizeof(var_sysStatisticsIndex) );
       var_sysStatisticsIndex.type = ASN_UNSIGNED;
       /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "sysStatisticsTable_extract_index index list not implemented!\n" );
    return 0;
#else
       //var_sysStatisticsIndex.next_variable = &var_XX;
#endif


    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes( hdr->oids, hdr->len, &var_sysStatisticsIndex );
    if (err == SNMP_ERR_NOERROR) {
       /*
        * copy components into the context structure
        */
                ctx->sysStatisticsIndex = *var_sysStatisticsIndex.val.integer;
   
   
           /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_sysStatisticsIndex.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_sysStatisticsIndex );

    return err;
}

/************************************************************
 * the *_can_delete routine is called to determine if a row
 * can be deleted.
 *
 * return 1 if the row can be deleted
 * return 0 if the row cannot be deleted
 */
int sysStatisticsTable_can_delete(sysStatisticsTable_context *undo_ctx,
                    sysStatisticsTable_context *row_ctx,
                    netsnmp_request_group * rg)
{
    
    /*
     * TODO: check for other deletion requirements here
     */
    return 1;
}

#ifdef sysStatisticsTable_ROW_CREATION
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated sysStatisticsTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
sysStatisticsTable_context *
sysStatisticsTable_create_row( netsnmp_index* hdr)
{
    sysStatisticsTable_context * ctx =
        SNMP_MALLOC_TYPEDEF(sysStatisticsTable_context);
    if(!ctx)
        return NULL;
        
    /*
     * TODO: check indexes, if necessary.
     */
    if(sysStatisticsTable_extract_index( ctx, hdr )) {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }

    /* netsnmp_mutex_init(ctx->lock);
       netsnmp_mutex_lock(ctx->lock); */

    /*
     * TODO: initialize any default values here. This is also
     * first place you really should allocate any memory for
     * yourself to use.  If you allocated memory earlier,
     * make sure you free it for earlier error cases!
     */
    /**
    */
     
    ctx->sysStatisticsPeriod = SYSSTAT_DEFAULT_PERIOD;
    ctx->sysStatTotalValue = 0;
    ctx->sysStatSquaresTotal = 0;
 	ctx->lastMaxValue = 0;
	ctx->lastMinValue = 0;
	ctx->lastTime=0;

    return ctx;
}
#endif

/************************************************************
 * the *_duplicate row routine
 */
sysStatisticsTable_context *
sysStatisticsTable_duplicate_row( sysStatisticsTable_context * row_ctx)
{
    sysStatisticsTable_context * dup;

    if(!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(sysStatisticsTable_context);
    if(!dup)
        return NULL;
        
    if(sysStatisticsTable_row_copy(dup,row_ctx)) {
        free(dup);
        dup = NULL;
    }

    return dup;
}

/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index * sysStatisticsTable_delete_row( sysStatisticsTable_context * ctx )
{
  /* netsnmp_mutex_destroy(ctx->lock); */

    if(ctx->index.oids)
        free(ctx->index.oids);

    /*
     * TODO: release any memory you allocated here...
     */

    /*
     * release header
     */
    free( ctx );

    return NULL;
}


/************************************************************
 * RESERVE is used to check the syntax of all the variables
 * provided, that the values being set are sensible and consistent,
 * and to allocate any resources required for performing the SET.
 * After this stage, the expectation is that the set ought to
 * succeed, though this is not guaranteed. (In fact, with the UCD
 * agent, this is done in two passes - RESERVE1, and
 * RESERVE2, to allow for dependancies between variables).
 *
 * BEFORE calling this routine, the agent will call duplicate_row
 * to create a copy of the row (unless this is a new row; i.e.
 * row_created == 1).
 *
 * next state -> SET_RESERVE2 || SET_FREE
 */
void sysStatisticsTable_set_reserve1( netsnmp_request_group *rg )
{
    sysStatisticsTable_context *row_ctx =
            (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx =
            (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_variable_list *var;
    netsnmp_request_group_item *current;
    int rc;


    /*
     * TODO: loop through columns, check syntax and lengths. For
     * columns which have no dependencies, you could also move
     * the value/range checking here to attempt to catch error
     * cases as early as possible.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->sysStatisticsPeriod));
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column in "
                     "sysStatisticsTable_set_reserve1\n");
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc );
        rg->status = SNMP_MAX( rg->status, current->ri->status );
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

void sysStatisticsTable_set_reserve2( netsnmp_request_group *rg )
{
    sysStatisticsTable_context *row_ctx = (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx = (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    netsnmp_variable_list *var;
    int rc;

    rg->rg_void = rg->list->ri;

    /*
     * TODO: loop through columns, check for valid
     * values and any range constraints.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * Assuming that the RESERVE phases were successful, the next
 * stage is indicated by the action value ACTION. This is used
 * to actually implement the set operation. However, this must
 * either be done into temporary (persistent) storage, or the
 * previous value stored similarly, in case any of the subsequent
 * ACTION calls fail.
 *
 * In your case, changes should be made to row_ctx. A copy of
 * the original row is in undo_ctx.
 */
void sysStatisticsTable_set_action( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    sysStatisticsTable_context *row_ctx = (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx = (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;


    /*
     * TODO: loop through columns, copy varbind values
     * to context structure for the row.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
            row_ctx->sysStatisticsPeriod = *var->val.integer;
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
    /*
     * TODO: if you have dependencies on other tables, this would be
     * a good place to check those, too.
     */
}

/************************************************************
 * Only once the ACTION phase has completed successfully, can
 * the final COMMIT phase be run. This is used to complete any
 * writes that were done into temporary storage, and then release
 * any allocated resources. Note that all the code in this phase
 * should be "safe" code that cannot possibly fail (cue
 * hysterical laughter). The whole intent of the ACTION/COMMIT
 * division is that all of the fallible code should be done in
 * the ACTION phase, so that it can be backed out if necessary.
 *
 * BEFORE calling this routine, the agent will update the
 * container (inserting a row if row_created == 1, or removing
 * the row if row_deleted == 1).
 *
 * AFTER calling this routine, the agent will delete the
 * undo_info.
 */
void sysStatisticsTable_set_commit( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    sysStatisticsTable_context *row_ctx = (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx = (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If either of the RESERVE calls fail, the write routines
 * are called again with the FREE action, to release any resources
 * that have been allocated. The agent will then return a failure
 * response to the requesting application.
 *
 * AFTER calling this routine, the agent will delete undo_info.
 */
void sysStatisticsTable_set_free( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    sysStatisticsTable_context *row_ctx = (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx = (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            /** should have been logged in reserve1 */
            break;
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If the ACTION phase does fail (for example due to an apparently
 * valid, but unacceptable value, or an unforeseen problem), then
 * the list of write routines are called again, with the UNDO
 * action. This requires the routine to reset the value that was
 * changed to its previous value (assuming it was actually changed),
 * and then to release any resources that had been allocated. As
 * with the FREE phase, the agent will then return an indication
 * of the error to the requesting application.
 *
 * BEFORE calling this routine, the agent will update the container
 * (remove any newly inserted row, re-insert any removed row).
 *
 * AFTER calling this routing, the agent will call row_copy
 * to restore the data in existing_row from the date in undo_info.
 * Then undo_info will be deleted (or existing row, if row_created
 * == 1).
 */
void sysStatisticsTable_set_undo( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    sysStatisticsTable_context *row_ctx = (sysStatisticsTable_context *)rg->existing_row;
    sysStatisticsTable_context *undo_ctx = (sysStatisticsTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

#endif /** sysStatisticsTable_SET_HANDLING */


/************************************************************
 *
 * Initialize the sysStatisticsTable table by defining its contents and how it's structured
 */
void
initialize_table_sysStatisticsTable(void)
{
    netsnmp_table_registration_info *table_info;

    if(my_handler) {
        snmp_log(LOG_ERR, "initialize_table_sysStatisticsTable_handler called again\n");
        return;
    }

    memset(&statcb, 0x00, sizeof(statcb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    /* if your table is read only, it's easiest to change the
       HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY */
    my_handler = netsnmp_create_handler_registration("sysStatisticsTable",
                                             netsnmp_table_array_helper_handler,
                                             sysStatisticsTable_oid,
                                             sysStatisticsTable_oid_len,
                                             HANDLER_CAN_RWRITE);
            
    if (!my_handler || !table_info) {
        snmp_log(LOG_ERR, "malloc failed in "
                 "initialize_table_sysStatisticsTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
        /** index: sysStatisticsIndex */
        netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = sysStatisticsTable_COL_MIN;
    table_info->max_column = sysStatisticsTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    statcb.get_value = sysStatisticsTable_get_value;
    statcb.container = netsnmp_container_find("sysStatisticsTable_primary:"
                                          "sysStatisticsTable:"
                                          "table_container");
#ifdef sysStatisticsTable_IDX2
    netsnmp_container_add_index(statcb.container,
                                netsnmp_container_find("sysStatisticsTable_secondary:"
                                                       "sysStatisticsTable:"
                                                       "table_container"));
    statcb.container->next->compare = sysStatisticsTable_cmp;
#endif
#ifdef sysStatisticsTable_SET_HANDLING
    statcb.can_set = 1;
#ifdef sysStatisticsTable_ROW_CREATION
    statcb.create_row = (UserRowMethod*)sysStatisticsTable_create_row;
#endif
    statcb.duplicate_row = (UserRowMethod*)sysStatisticsTable_duplicate_row;
    statcb.delete_row = (UserRowMethod*)sysStatisticsTable_delete_row;
    statcb.row_copy = (Netsnmp_User_Row_Operation *)sysStatisticsTable_row_copy;

    statcb.can_delete = (Netsnmp_User_Row_Action *)sysStatisticsTable_can_delete;

    statcb.set_reserve1 = sysStatisticsTable_set_reserve1;
    statcb.set_reserve2 = sysStatisticsTable_set_reserve2;
    statcb.set_action = sysStatisticsTable_set_action;
    statcb.set_commit = sysStatisticsTable_set_commit;
    statcb.set_free = sysStatisticsTable_set_free;
    statcb.set_undo = sysStatisticsTable_set_undo;
#endif
    DEBUGMSGTL(("initialize_table_sysStatisticsTable",
                "Registering table sysStatisticsTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &statcb,
                                     statcb.container, 1);
}

/************************************************************
 * sysStatisticsTable_get_value
 */
int sysStatisticsTable_get_value(
            netsnmp_request_info *request,
            netsnmp_index *item,
            netsnmp_table_request_info *table_info )
{
    netsnmp_variable_list *var = request->requestvb;
    sysStatisticsTable_context *context = (sysStatisticsTable_context *)item;

    switch(table_info->colnum) {

        case COLUMN_SYSSTATISTICSINDEX:
            /** UNSIGNED32 = ASN_UNSIGNED */
            snmp_set_var_typed_value(var, ASN_UNSIGNED,
                         (char*)&context->sysStatisticsIndex,
                         sizeof(context->sysStatisticsIndex) );
        break;
    
        case COLUMN_SYSSTATISTICSVARIABLE:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->sysStatisticsVariable,
                         context->sysStatisticsVariable_len );
        break;
    
        case COLUMN_SYSSTATISTICSPERIOD:
            /** INTEGER = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->sysStatisticsPeriod,
                         sizeof(context->sysStatisticsPeriod) );
        break;
    
        case COLUMN_SYSSTATISTICSMAXVALUE:
            /** INTEGER32 = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->sysStatisticsMaxValue,
                         sizeof(context->sysStatisticsMaxValue) );
        break;
    
        case COLUMN_SYSSTATISTICSMINVALUE:
            /** INTEGER32 = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->sysStatisticsMinValue,
                         sizeof(context->sysStatisticsMinValue) );
        break;
    
        case COLUMN_SYSSTATISTICSAVGVALUE:
            /** INTEGER32 = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->sysStatisticsAvgValue,
                         sizeof(context->sysStatisticsAvgValue) );
        break;
    
        case COLUMN_SYSSTATISTICSSTD:
            /** INTEGER32 = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->sysStatisticsStd,
                         sizeof(context->sysStatisticsStd) );
        break;
    
    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                 "sysStatisticsTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * sysStatisticsTable_get_by_idx
 */
const sysStatisticsTable_context *
sysStatisticsTable_get_by_idx(netsnmp_index * hdr)
{
    return (const sysStatisticsTable_context *)
        CONTAINER_FIND(statcb.container, hdr );
}


/* <Start: WIP_NURI_ALL > */

float getSquareRoot(float a) {
  int i;
  float x;
  
  x = 1.0;

  for ( i = 0; i < 10; i++ ) {

    x = ( x + ( a / x ) ) / 2.0;

  }

  return x;

}


void updateRow(long index, long val) {
	sysStatisticsTable_context *statCtx = NULL;
	netsnmp_index statIndex;
	oid indexOID=0;
	statIndex.len=1;
	indexOID = (oid) index;
	statIndex.oids = &indexOID;
	statCtx = CONTAINER_FIND(statcb.container, &statIndex);
	if(statCtx) {
		statCtx->sampleCount++;
		statCtx->lastTime+=RTM_DEFAULT_INTERVAL;

		if(statCtx->lastMaxValue < val) {
			statCtx->lastMaxValue = val;
		}
		
		if(statCtx->lastMinValue> val || statCtx->lastMinValue==0){
			statCtx->lastMinValue = val;
		}

		statCtx->sysStatTotalValue+=val;
		statCtx->sysStatSquaresTotal =
			(statCtx->sysStatSquaresTotal + (val*val));
		if(statCtx->lastTime>=statCtx->sysStatisticsPeriod){
			statCtx->sysStatisticsMaxValue = statCtx->lastMaxValue;
			statCtx->lastMaxValue=0;
			
			statCtx->sysStatisticsMinValue = statCtx->lastMinValue;
			statCtx->lastMinValue=0;

			statCtx->sysStatisticsAvgValue = 
						(statCtx->sysStatTotalValue/statCtx->sampleCount);
			statCtx->sysStatisticsStd =
				getSquareRoot( (double) ((2*statCtx->sysStatisticsAvgValue*
							statCtx->sysStatTotalValue) + 
						(statCtx->sampleCount*statCtx->sysStatisticsAvgValue*
							statCtx->sysStatisticsAvgValue) - 
							statCtx->sysStatSquaresTotal ) 
							 / statCtx->sampleCount );
									
			statCtx->sysStatTotalValue=0;
			statCtx->sampleCount = 0;
			statCtx->lastTime=0;
			statCtx->sysStatSquaresTotal=0;
		}
	}	
}

void destroySysStatRow(long index) {
	sysStatisticsTable_context *statCtx = NULL;
	netsnmp_index statIndex;
	oid indexOID=0;
	statIndex.len=1;
	indexOID = (oid) index;
	statIndex.oids = &indexOID;
	statCtx = CONTAINER_FIND(statcb.container, &statIndex);
	if(statCtx){
		CONTAINER_REMOVE(statcb.container, statCtx);
	}
}


void createSysStatRow(long index, oid *variable, long varLen){ 
	netsnmp_index statIndex;
	int rowAlreadyPresent=0;
	char temp[10];
	int i=0;
	oid indexOID=0;
	sysStatisticsTable_context *sysStatRow = NULL;
	statIndex.len=1;
	indexOID = (oid) index;
	statIndex.oids = &indexOID;
	sysStatRow = CONTAINER_FIND(statcb.container,&statIndex);
	if(sysStatRow == NULL) {
		sysStatRow = sysStatisticsTable_create_row(&statIndex);
	}else{
		rowAlreadyPresent=1;
	}
	sysStatRow->sysStatisticsVariable[0] = '\0';
	for(i=0;i<(varLen/sizeof(oid));i++) {
		sprintf(temp, ".%d", variable[i]);
		strcat(sysStatRow->sysStatisticsVariable, temp);
	}
	sysStatRow->sysStatisticsVariable_len = 
			strlen(sysStatRow->sysStatisticsVariable);
	if(rowAlreadyPresent==0){
		CONTAINER_INSERT(statcb.container,sysStatRow);
	}
}

/* <End: WIP_NURI_ALL > */
