/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.1 2003/10/11 09:58:35 rajesh Exp $
 */
#ifndef ALLOWTELNETTABLE_H
#define ALLOWTELNETTABLE_H

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* 
 * allowTelnetTable_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid allowTelnetTable_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3};

oid allowTelenetIndex_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3,1,1};
oid allowTelenetID_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3,1,2};
oid allowTelenetIPAddress_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3,1,3};
oid allowTelenetPortNo_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3,1,4};
oid allowTelnetStatus_variables_oid[] = { 1,3,6,1,4,1,3204,1,3,34,4,3,1,5};

#endif /* ALLOWTELNETTABLE_H */
