/*
 * Note: this file originally auto-generated by mib2c using
 *       : mib2c.array-user.conf,v 5.15.2.1 2003/02/27 05:59:41 rstory Exp $
 *
 * $Id: NASCenter_UM_Linux_allowPOP3Table.c,v 1.2 2003/11/24 05:43:18 guga Exp $
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial/
 *
 *
 * You can also join the #net-snmp channel on irc.openprojects.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "allowPOP3Table.h"

static     netsnmp_handler_registration *my_handler = NULL;
static     netsnmp_table_array_callbacks cb;

oid allowPOP3Table_oid[] = { allowPOP3Table_TABLE_OID };
size_t allowPOP3Table_oid_len = OID_LENGTH(allowPOP3Table_oid);


#ifdef allowPOP3Table_IDX2
/************************************************************
 * keep binary tree to find context by name
 */
static int allowPOP3Table_cmp( const void *lhs, const void *rhs );

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
allowPOP3Table_cmp( const void *lhs, const void *rhs )
{
    allowPOP3Table_context *context_l =
        (allowPOP3Table_context *)lhs;
    allowPOP3Table_context *context_r =
        (allowPOP3Table_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 indexes
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "allowPOP3Table_compare not implemented! Container order undefined\n" );
    return 0;
#endif
    
    /*
     * EXAMPLE:
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName);
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
allowPOP3Table_context *
allowPOP3Table_get( const char *name, int len )
{
    allowPOP3Table_context tmp;

    /** we should have a secondary index */
    netsnmp_assert(cb.container->next != NULL);
    
    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "allowPOP3Table_get not implemented!\n" );
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif


/************************************************************
 * Initializes the allowPOP3Table module
 */
void
init_allowPOP3Table(void)
{
    initialize_table_allowPOP3Table();

    /*
     * TODO: perform any startup stuff here
     */
}

/************************************************************
 * the *_row_copy routine
 */
static int allowPOP3Table_row_copy(allowPOP3Table_context * dst,
                         allowPOP3Table_context * src)
{
    if(!dst||!src)
        return 1;
        
    /*
     * copy index, if provided
     */
    if(dst->index.oids)
        free(dst->index.oids);
    if(snmp_clone_mem( (void*)&dst->index.oids, src->index.oids,
                           src->index.len * sizeof(oid) )) {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    

    /*
     * copy components into the context structure
     */
    dst->allowPOP3Index = src->allowPOP3Index;

    memcpy( dst->allowPOP3ID, src->allowPOP3ID, src->allowPOP3ID_len );
    dst->allowPOP3ID_len = src->allowPOP3ID_len;

    memcpy( dst->allowPOP3IPAddress, src->allowPOP3IPAddress, src->allowPOP3IPAddress_len );
    dst->allowPOP3IPAddress_len = src->allowPOP3IPAddress_len;

    dst->allowPOP3PortNo = src->allowPOP3PortNo;

    dst->allowPOP3Status = src->allowPOP3Status;

    return 0;
}

#ifdef allowPOP3Table_SET_HANDLING

/*
 * the *_extract_index routine
 */
int
allowPOP3Table_extract_index( allowPOP3Table_context * ctx, netsnmp_index * hdr )
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_allowPOP3Index;
    int err;

    /*
     * copy index, if provided
     */
    if(hdr) {
        netsnmp_assert(ctx->index.oids == NULL);
        if(snmp_clone_mem( (void*)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid) )) {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /**
     * Create variable to hold each component of the index
     */
       memset( &var_allowPOP3Index, 0x00, sizeof(var_allowPOP3Index) );
       var_allowPOP3Index.type = ASN_UNSIGNED;
       /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "allowPOP3Table_extract_index index list not implemented!\n" );
    return 0;
#else
     //  var_allowPOP3Index.next_variable = &var_XX;
#endif


    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes( hdr->oids, hdr->len, &var_allowPOP3Index );
    if (err == SNMP_ERR_NOERROR) {
       /*
        * copy components into the context structure
        */
                ctx->allowPOP3Index = *var_allowPOP3Index.val.integer;
   
   
           /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_allowPOP3Index.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_allowPOP3Index );

    return err;
}

/************************************************************
 * the *_can_activate routine is called
 * when a row is changed to determine if all the values
 * set are consistent with the row's rules for a row status
 * of ACTIVE.
 *
 * return 1 if the row could be ACTIVE
 * return 0 if the row is not ready for the ACTIVE state
 */
int allowPOP3Table_can_activate(allowPOP3Table_context *undo_ctx,
                      allowPOP3Table_context *row_ctx,
                      netsnmp_request_group * rg)
{
    /*
     * TODO: check for activation requirements here
     */
    return 1;
}

/************************************************************
 * the *_can_deactivate routine is called when a row that is
 * currently ACTIVE is set to a state other than ACTIVE. If
 * there are conditions in which a row should not be allowed
 * to transition out of the ACTIVE state (such as the row being
 * referred to by another row or table), check for them here.
 *
 * return 1 if the row can be set to a non-ACTIVE state
 * return 0 if the row must remain in the ACTIVE state
 */
int allowPOP3Table_can_deactivate(allowPOP3Table_context *undo_ctx,
                        allowPOP3Table_context *row_ctx,
                        netsnmp_request_group * rg)
{
    /*
     * TODO: check for deactivation requirements here
     */
    return 1;
}

/************************************************************
 * the *_can_delete routine is called to determine if a row
 * can be deleted.
 *
 * return 1 if the row can be deleted
 * return 0 if the row cannot be deleted
 */
int allowPOP3Table_can_delete(allowPOP3Table_context *undo_ctx,
                    allowPOP3Table_context *row_ctx,
                    netsnmp_request_group * rg)
{
    /*
     * probably shouldn't delete a row that we can't
     * deactivate.
     */
    if(allowPOP3Table_can_deactivate(undo_ctx,row_ctx,rg) != 1)
        return 0;
    
    /*
     * TODO: check for other deletion requirements here
     */
    return 1;
}

#ifdef allowPOP3Table_ROW_CREATION
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated allowPOP3Table_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
allowPOP3Table_context *
allowPOP3Table_create_row( netsnmp_index* hdr)
{
    allowPOP3Table_context * ctx =
        SNMP_MALLOC_TYPEDEF(allowPOP3Table_context);
    if(!ctx)
        return NULL;
        
    /*
     * TODO: check indexes, if necessary.
     */
    if(allowPOP3Table_extract_index( ctx, hdr )) {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }

    /* netsnmp_mutex_init(ctx->lock);
       netsnmp_mutex_lock(ctx->lock); */

    /*
     * TODO: initialize any default values here. This is also
     * first place you really should allocate any memory for
     * yourself to use.  If you allocated memory earlier,
     * make sure you free it for earlier error cases!
     */
    /**
     ctx->allowPOP3ID = 0;
     ctx->allowPOP3IPAddress = 0;
     ctx->allowPOP3PortNo = 0;
     ctx->allowPOP3Status = 0;
    */

    return ctx;
}
#endif

/************************************************************
 * the *_duplicate row routine
 */
allowPOP3Table_context *
allowPOP3Table_duplicate_row( allowPOP3Table_context * row_ctx)
{
    allowPOP3Table_context * dup;

    if(!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(allowPOP3Table_context);
    if(!dup)
        return NULL;
        
    if(allowPOP3Table_row_copy(dup,row_ctx)) {
        free(dup);
        dup = NULL;
    }

    return dup;
}

/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index * allowPOP3Table_delete_row( allowPOP3Table_context * ctx )
{
  /* netsnmp_mutex_destroy(ctx->lock); */

    if(ctx->index.oids)
        free(ctx->index.oids);

    /*
     * TODO: release any memory you allocated here...
     */

    /*
     * release header
     */
    free( ctx );

    return NULL;
}


/************************************************************
 * RESERVE is used to check the syntax of all the variables
 * provided, that the values being set are sensible and consistent,
 * and to allocate any resources required for performing the SET.
 * After this stage, the expectation is that the set ought to
 * succeed, though this is not guaranteed. (In fact, with the UCD
 * agent, this is done in two passes - RESERVE1, and
 * RESERVE2, to allow for dependancies between variables).
 *
 * BEFORE calling this routine, the agent will call duplicate_row
 * to create a copy of the row (unless this is a new row; i.e.
 * row_created == 1).
 *
 * next state -> SET_RESERVE2 || SET_FREE
 */
void allowPOP3Table_set_reserve1( netsnmp_request_group *rg )
{
    allowPOP3Table_context *row_ctx =
            (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx =
            (allowPOP3Table_context *)rg->undo_info;
    netsnmp_variable_list *var;
    netsnmp_request_group_item *current;
    int rc;


    /*
     * TODO: loop through columns, check syntax and lengths. For
     * columns which have no dependencies, you could also move
     * the value/range checking here to attempt to catch error
     * cases as early as possible.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                                //sizeof(row_ctx->allowPOP3ID)
var->val_len);
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
            rc = netsnmp_check_vb_type_and_size(var, ASN_OCTET_STR,
                                               // sizeof(row_ctx->allowPOP3IPAddress)
var->val_len);
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->allowPOP3PortNo));
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
            rc = netsnmp_check_vb_type_and_size(var, ASN_INTEGER,
                                                sizeof(row_ctx->allowPOP3Status));
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column in "
                     "allowPOP3Table_set_reserve1\n");
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc );
        rg->status = SNMP_MAX( rg->status, current->ri->status );
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

void allowPOP3Table_set_reserve2( netsnmp_request_group *rg )
{
    allowPOP3Table_context *row_ctx = (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx = (allowPOP3Table_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    netsnmp_variable_list *var;
    int rc;

    rg->rg_void = rg->list->ri;

    /*
     * TODO: loop through columns, check for valid
     * values and any range constraints.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
                    /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
                rc = netsnmp_check_vb_rowstatus(current->ri->requestvb,
                                                undo_ctx ?
                                                undo_ctx->allowPOP3Status:0);
                rg->rg_void = current->ri;
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }

        if (rc)
           netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * Assuming that the RESERVE phases were successful, the next
 * stage is indicated by the action value ACTION. This is used
 * to actually implement the set operation. However, this must
 * either be done into temporary (persistent) storage, or the
 * previous value stored similarly, in case any of the subsequent
 * ACTION calls fail.
 *
 * In your case, changes should be made to row_ctx. A copy of
 * the original row is in undo_ctx.
 */
void allowPOP3Table_set_action( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    allowPOP3Table_context *row_ctx = (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx = (allowPOP3Table_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    int            row_err = 0;

    /*
     * TODO: loop through columns, copy varbind values
     * to context structure for the row.
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
            memcpy(row_ctx->allowPOP3ID,var->val.string,var->val_len);
            row_ctx->allowPOP3ID_len = var->val_len;
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
            memcpy(row_ctx->allowPOP3IPAddress,var->val.string,var->val_len);
            row_ctx->allowPOP3IPAddress_len = var->val_len;
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
            row_ctx->allowPOP3PortNo = *var->val.integer;
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
            row_ctx->allowPOP3Status = *var->val.integer;
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
#ifndef allowPOP3Table_CAN_MODIFY_ACTIVE_ROW
    if( undo_ctx && RS_IS_ACTIVE(undo_ctx->allowPOP3Status) &&
        row_ctx && RS_IS_ACTIVE(row_ctx->allowPOP3Status) ) {
            row_err = 1;
    }
#endif

    /*
     * check activation/deactivation
     */
    row_err = netsnmp_table_array_check_row_status(&cb, rg,
                                  row_ctx ? &row_ctx->allowPOP3Status : NULL,
                                  undo_ctx ? &undo_ctx->allowPOP3Status : NULL);
    if(row_err) {
        netsnmp_set_mode_request_error(MODE_SET_BEGIN,
                                       (netsnmp_request_info*)rg->rg_void,
                                       row_err);
        return;
    }

    /*
     * TODO: if you have dependencies on other tables, this would be
     * a good place to check those, too.
     */
}

/************************************************************
 * Only once the ACTION phase has completed successfully, can
 * the final COMMIT phase be run. This is used to complete any
 * writes that were done into temporary storage, and then release
 * any allocated resources. Note that all the code in this phase
 * should be "safe" code that cannot possibly fail (cue
 * hysterical laughter). The whole intent of the ACTION/COMMIT
 * division is that all of the fallible code should be done in
 * the ACTION phase, so that it can be backed out if necessary.
 *
 * BEFORE calling this routine, the agent will update the
 * container (inserting a row if row_created == 1, or removing
 * the row if row_deleted == 1).
 *
 * AFTER calling this routine, the agent will delete the
 * undo_info.
 */
void allowPOP3Table_set_commit( netsnmp_request_group *rg )
{
    stVarBindArgs stargs[NO_OF_FIELDS];
    char acstrTmpOID[MAX_VAR_LEN];
    int icnt;
    short srecCount = 0;
    netsnmp_variable_list *var;
    netsnmp_variable_list *varCopy;

    allowPOP3Table_context *row_ctx = (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx = (allowPOP3Table_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    var=rg->list->ri->requestvb;
    printf("Copying varbind: allowPOP3Table\n");
    varCopy=snmp_clone_varbind(var);
    printf("Sending Trap from alloPOP3Table\n");
    send_v2trap(varCopy);
    printf("Send Trap : allowPOP3Table\n");

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

         var = current->ri->requestvb;
        strcpy(acstrTmpOID,"");
        memset(stargs[srecCount].acVariable,0,sizeof(stargs[srecCount].acVariable));
        for(icnt=0;icnt<var->name_length;icnt++)
        {
          sprintf(acstrTmpOID, ".%lu",var->name[icnt]);
          strcat (stargs[srecCount].acVariable,acstrTmpOID);
        }//for icnt
    printf("Variable: %s\n",stargs[srecCount].acVariable);
    switch ((short) var->type)
    {
       case ASN_INTEGER:
          stargs[srecCount].cType='i';
          printf("Type is integer : %d\n",(short) var->type);
          printf("Value: %d\n",*(var->val.integer));
          memset (stargs[srecCount].pcValue, '\0', sizeof (stargs[srecCount].pcValue));
          sprintf (stargs[srecCount].pcValue, "%ld",  *(var->val.integer));
          printf("****** After copying args[%d].pcValue=%s\n",
                    srecCount, stargs[srecCount].pcValue);
       break;

       case ASN_OCTET_STR:
          stargs[srecCount].cType='s';
          printf("Type is an OCTET string\n");
          printf("%d\n",(short) var->type);
          printf("Value: %s\n",var->val.string);
          memset (stargs[srecCount].pcValue,'\0',sizeof (stargs[srecCount].pcValue));
          strcpy (stargs[srecCount].pcValue, var->val.string);
          printf("Value after copying: %s\n",stargs[srecCount].pcValue);
       break;

       default:
          printf ("WARNING: TYPE NOT HANDLED....\n");
       break;
    }//switch         
        
    srecCount++; 

   switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }
        allowPOP3Table_send_snmptrap(srecCount,stargs,200);
    printf("Code exited with %d\n",icnt);



    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If either of the RESERVE calls fail, the write routines
 * are called again with the FREE action, to release any resources
 * that have been allocated. The agent will then return a failure
 * response to the requesting application.
 *
 * AFTER calling this routine, the agent will delete undo_info.
 */
void allowPOP3Table_set_free( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    allowPOP3Table_context *row_ctx = (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx = (allowPOP3Table_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            /** should have been logged in reserve1 */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If the ACTION phase does fail (for example due to an apparently
 * valid, but unacceptable value, or an unforeseen problem), then
 * the list of write routines are called again, with the UNDO
 * action. This requires the routine to reset the value that was
 * changed to its previous value (assuming it was actually changed),
 * and then to release any resources that had been allocated. As
 * with the FREE phase, the agent will then return an indication
 * of the error to the requesting application.
 *
 * BEFORE calling this routine, the agent will update the container
 * (remove any newly inserted row, re-insert any removed row).
 *
 * AFTER calling this routing, the agent will call row_copy
 * to restore the data in existing_row from the date in undo_info.
 * Then undo_info will be deleted (or existing row, if row_created
 * == 1).
 */
void allowPOP3Table_set_undo( netsnmp_request_group *rg )
{
    netsnmp_variable_list *var;
    allowPOP3Table_context *row_ctx = (allowPOP3Table_context *)rg->existing_row;
    allowPOP3Table_context *undo_ctx = (allowPOP3Table_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for( current = rg->list; current; current = current->next ) {

        var = current->ri->requestvb;

        switch(current->tri->colnum) {

        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
        break;

        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
        break;

        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
        break;

        default: /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

#endif /** allowPOP3Table_SET_HANDLING */


/************************************************************
 *
 * Initialize the allowPOP3Table table by defining its contents and how it's structured
 */
void
initialize_table_allowPOP3Table(void)
{
    netsnmp_table_registration_info *table_info;

    if(my_handler) {
        snmp_log(LOG_ERR, "initialize_table_allowPOP3Table_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    /* if your table is read only, it's easiest to change the
       HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY */
    my_handler = netsnmp_create_handler_registration("allowPOP3Table",
                                             netsnmp_table_array_helper_handler,
                                             allowPOP3Table_oid,
                                             allowPOP3Table_oid_len,
                                             HANDLER_CAN_RWRITE);
            
    if (!my_handler || !table_info) {
        snmp_log(LOG_ERR, "malloc failed in "
                 "initialize_table_allowPOP3Table_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
        /** index: allowPOP3Index */
        netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = allowPOP3Table_COL_MIN;
    table_info->max_column = allowPOP3Table_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = allowPOP3Table_get_value;
    cb.container = netsnmp_container_find("allowPOP3Table_primary:"
                                          "allowPOP3Table:"
                                          "table_container");
#ifdef allowPOP3Table_IDX2
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("allowPOP3Table_secondary:"
                                                       "allowPOP3Table:"
                                                       "table_container"));
    cb.container->next->compare = allowPOP3Table_cmp;
#endif
#ifdef allowPOP3Table_SET_HANDLING
    cb.can_set = 1;
#ifdef allowPOP3Table_ROW_CREATION
    cb.create_row = (UserRowMethod*)allowPOP3Table_create_row;
#endif
    cb.duplicate_row = (UserRowMethod*)allowPOP3Table_duplicate_row;
    cb.delete_row = (UserRowMethod*)allowPOP3Table_delete_row;
    cb.row_copy = (Netsnmp_User_Row_Operation *)allowPOP3Table_row_copy;

    cb.can_activate = (Netsnmp_User_Row_Action *)allowPOP3Table_can_activate;
    cb.can_deactivate = (Netsnmp_User_Row_Action *)allowPOP3Table_can_deactivate;
    cb.can_delete = (Netsnmp_User_Row_Action *)allowPOP3Table_can_delete;

    cb.set_reserve1 = allowPOP3Table_set_reserve1;
    cb.set_reserve2 = allowPOP3Table_set_reserve2;
    cb.set_action = allowPOP3Table_set_action;
    cb.set_commit = allowPOP3Table_set_commit;
    cb.set_free = allowPOP3Table_set_free;
    cb.set_undo = allowPOP3Table_set_undo;
#endif
    DEBUGMSGTL(("initialize_table_allowPOP3Table",
                "Registering table allowPOP3Table "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * allowPOP3Table_get_value
 */
int allowPOP3Table_get_value(
            netsnmp_request_info *request,
            netsnmp_index *item,
            netsnmp_table_request_info *table_info )
{
    netsnmp_variable_list *var = request->requestvb;
    allowPOP3Table_context *context = (allowPOP3Table_context *)item;

    switch(table_info->colnum) {

        case COLUMN_ALLOWPOP3INDEX:
            /** UNSIGNED32 = ASN_UNSIGNED */
            snmp_set_var_typed_value(var, ASN_UNSIGNED,
                         (char*)&context->allowPOP3Index,
                         sizeof(context->allowPOP3Index) );
        break;
    
        case COLUMN_ALLOWPOP3ID:
            /** DisplayString = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->allowPOP3ID,
                         context->allowPOP3ID_len );
        break;
    
        case COLUMN_ALLOWPOP3IPADDRESS:
            /** OCTETSTR = ASN_OCTET_STR */
            snmp_set_var_typed_value(var, ASN_OCTET_STR,
                         (char*)&context->allowPOP3IPAddress,
                         context->allowPOP3IPAddress_len );
        break;
    
        case COLUMN_ALLOWPOP3PORTNO:
            /** INTEGER = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->allowPOP3PortNo,
                         sizeof(context->allowPOP3PortNo) );
        break;
    
        case COLUMN_ALLOWPOP3STATUS:
            /** RowStatus = ASN_INTEGER */
            snmp_set_var_typed_value(var, ASN_INTEGER,
                         (char*)&context->allowPOP3Status,
                         sizeof(context->allowPOP3Status) );
        break;
    
    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                 "allowPOP3Table_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * allowPOP3Table_get_by_idx
 */
const allowPOP3Table_context *
allowPOP3Table_get_by_idx(netsnmp_index * hdr)
{
    return (const allowPOP3Table_context *)
        CONTAINER_FIND(cb.container, hdr );
}

int allowPOP3Table_send_snmptrap (int length, stVarBindArgs *stTrapPDU, int port)
{
    netsnmp_session session, *ss;
    netsnmp_pdu       *pdu, *response;
    in_addr_t       *pdu_in_addr_t;
    oid            name[MAX_OID_LEN];
    size_t         name_length;
    int            arg;
    int            status;
    char       *trap = NULL, *specific = NULL, *description =
    NULL, *agent = NULL;
    char       *prognam;
    int            exitval = 0;
    int            icnt = 0;
    char**        argv;
    int            argc;
    struct in_addr  laddr;
    netsnmp_variable_list *tempPtr;
    char * value; 
    int intValue;
  
   printf("trapPDU var=%s type=%c val=%s\n", stTrapPDU[0].acVariable,
             stTrapPDU[0].cType, stTrapPDU[0].pcValue);

    /** initialize session to default values*/
     
    snmp_sess_init (&session);


    /* Initialize session values - DUMMY */
    session.version = SNMP_VERSION_2c;
    session.timeout = 1 * 1000000L;
    session.retries = 3;
    session.community = (unsigned char *) "public";
    session.community_len = strlen (session.community);

     
    session.peername = "localhost";

    /*DEBUGMSGTL(("send_snmptrap", "trapIP=%lu peername=%s trapPort=%ld\n",
                ctx->trapDestinationIP, session.peername, ctx->trapPort));*/

    SOCK_STARTUP;

    session.callback = allowPOP3Table_snmp_input;
    session.callback_magic = NULL;

    
    netsnmp_ds_set_int(NETSNMP_DS_LIBRARY_ID, NETSNMP_DS_LIB_DEFAULT_PORT,
               (int) port);

    if (session.version == SNMP_VERSION_3) {
    /*
     * for traps, we use ourselves as the authoritative engine
     * which is really stupid since command line apps don't have a
     * notion of a persistent engine.  Hence, our boots and time
     * values are probably always really wacked with respect to what
     * a manager would like to see.
     *
     * The following should be enough to:
     *
     * 1) prevent the library from doing discovery for engineid & time.
     * 2) use our engineid instead of the remote engineid for
     * authoritative & privacy related operations.
     * 3) The remote engine must be configured with users for our engineID.
     *
     * -- Wes
     */

    /*
     * setup the engineID based on IP addr.     Need a different
     * algorthim here.  This will cause problems with agents on the
     * same machine sending traps.
     */
    setup_engineID(NULL, NULL);

    /*
     * pick our own engineID
     */
    if (session.securityEngineIDLen == 0 ||
        session.securityEngineID == NULL) {
        session.securityEngineID =
        snmpv3_generate_engineID(&session.securityEngineIDLen);
    }
    if (session.contextEngineIDLen == 0 ||
        session.contextEngineID == NULL) {
        session.contextEngineID =
        snmpv3_generate_engineID(&session.contextEngineIDLen);
    }

    /*
     * set boots and time, which will cause problems if this
     * machine ever reboots and a remote trap receiver has cached our
     * boots and time...  I'll cause a not-in-time-window report to
     * be sent back to this machine.
     */
    if (session.engineBoots == 0)
        session.engineBoots = 1;
    if (session.engineTime == 0)    /* not really correct, */
        session.engineTime = get_uptime();    /* but it'll work. Sort of. */
    }

    ss = snmp_open(&session);
    if (ss == NULL) {
    /*
     * diagnose snmp_open errors with the input netsnmp_session pointer
     */
    snmp_sess_perror("snmptrap", &session);

    SOCK_CLEANUP;
    exit(1);
    }

    if (session.version == SNMP_VERSION_1) {
    pdu = snmp_pdu_create(SNMP_MSG_TRAP);
    pdu_in_addr_t = (in_addr_t *) pdu->agent_addr;

    /*if (argv[arg][0] == 0) {

        pdu->enterprise = (oid *) malloc(sizeof(objid_enterprise));
        memcpy(pdu->enterprise, objid_enterprise,
           sizeof(objid_enterprise));
        pdu->enterprise_length =
        sizeof(objid_enterprise) / sizeof(oid);
    } else {
        name_length = MAX_OID_LEN;
        if (!snmp_parse_oid(argv[arg], name, &name_length)) {
        snmp_perror(argv[arg]);
        /* usage(); - DUMMY 
        SOCK_CLEANUP;
        exit(1);
        }*/
       /* pdu->enterprise = (oid *) malloc(name_length * sizeof(oid));
        memcpy(pdu->enterprise, name, name_length * sizeof(oid));
        pdu->enterprise_length = name_length;
    }*/

    if (++arg >= argc) {
        fprintf(stderr, "Missing agent parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    agent = argv[arg];
    if (agent != NULL && strlen(agent) != 0) {
      //  *pdu_in_addr_t = parse_address(agent);
    } else {
        *pdu_in_addr_t = get_myaddr();
    }
    if (++arg == argc) {
        fprintf(stderr, "Missing generic-trap parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    trap = argv[arg];
    pdu->trap_type = atoi(trap);
    if (++arg == argc) {
        fprintf(stderr, "Missing specific-trap parameter\n");
        /* usage(); - DUMMY */
        SOCK_CLEANUP;
        exit(1);
    }
    specific = argv[arg];
    pdu->specific_type = atoi(specific);
    if (++arg == argc) {
        fprintf(stderr, "Missing uptime parameter\n");
        /* usage() - DUMMY */;
        SOCK_CLEANUP;
        exit(1);
    }
    description = argv[arg];
    if (description == NULL || *description == 0)
        pdu->time = get_uptime();
    else
        pdu->time = atol(description);
    } else {
    long        sysuptime;
    char        csysuptime[20];

    pdu = snmp_pdu_create(SNMP_MSG_TRAP2);

    /* trap = argv[arg]; */ /* This is sysuptime */
    /* Always get the sysuptime from system, temporarily set *trap=0 */

    sysuptime = get_uptime();
    sprintf(csysuptime, "%ld", sysuptime);
    trap = csysuptime;

    /*snmp_add_var(pdu, objid_sysuptime,
             sizeof(objid_sysuptime) / sizeof(oid), 't', trap);*/

   /* if (snmp_add_var
        (pdu, objid_snmptrap, sizeof(objid_snmptrap) / sizeof(oid),
         'o', NURI_ENTERPRISE_OID) != 0) {
        
        printf ("***** objid_snmptrap problem...exiting....\n");
        SOCK_CLEANUP;
        exit(1);
    }*/
    }
    name_length = MAX_OID_LEN;
    for (icnt = 0; icnt < length; icnt++)
    {
        if (!snmp_parse_oid(stTrapPDU[icnt].acVariable, name, &name_length)) {
           printf("OID: %s\n",stTrapPDU[icnt].acVariable);
           printf ("****** argument oid problem.................\n");
           SOCK_CLEANUP;
           exit(1);
        }
        if (snmp_add_var
        (pdu, name, name_length, stTrapPDU[icnt].cType, stTrapPDU[icnt].pcValue) != 0) {
           printf ("****** name=%s name_length=%d SNMPTRAP argument type and value problem..............\n", name, name_length);
           SOCK_CLEANUP;
           exit(1);
        }
    }//for
    status = snmp_send(ss, pdu) == 0;
    if (status) {
    snmp_sess_perror("snmptrap", ss);
    snmp_free_pdu(pdu);
    exitval = 1;
  }

    snmp_close(ss);
    SOCK_CLEANUP;
    printf("Finishing sndtrap\n");
    return exitval;
}

/*****************************************************************************
 * name             :   allowPOP3Table_snmp_input
 * description      :   This is a callback function for sending trap
 * input parameters :
 * output parameters:
 * return type      :   int
 * global variables :
 * calls            :   allowPOP3Table_send_snmptrap
 *****************************************************************************/

static int
allowPOP3Table_snmp_input(int operation,
       netsnmp_session * session,
       int reqid, netsnmp_pdu *pdu, void *magic)
{
    return 1;
}

