/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */

static int coun;
static long fs[10];

#ifndef HRDISKSTORAGEENTRY_H
#define HRDISKSTORAGEENTRY_H


/* function declarations */
void init_hrDiskStorageEntry(void);
FindVarMethod var_hrDiskStorageEntry;

#endif /* HRDISKSTORAGEENTRY_H */
