/*****************************************************************************
 *
 * hrSWRunPerfEntry_Win.h
 *
 *      Copyright (c) 2002 Wipro Technologies
 *      All right Reserved
 *
 * author:
 *      Ashok Shankar
 *
 *
 * description:
 *      hrSWRunPerfEntry_Win.h provides common includes,macros,and external
 *              declarations/definitions for users of hrSWRunPerfEntry_Win.c
 *
 * CM Details:
 *
 * $Author: ashok $
 * $Log: hrSWRunPerfEntry_Win.h,v $
 * Revision 1.2  2003/11/11 13:41:43  ashok
 * Minor Corrections
 *
 * Revision 1.1  2003/10/31 12:08:44  ashok
 * Added into CVS by Ashok
 *
 * $State: Exp $
 * $Id: hrSWRunPerfEntry_Win.h,v 1.2 2003/11/11 13:41:43 ashok Exp $
 * $Name: NASCenterAgent_29Jan2004_Patch3_SrcRls $
 *
 ****************************************************************************/
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3 2002/10/17 09:40:46 dts12 Exp $
 */
#ifndef HRSWRUNPERFENTRY_H
#define HRSWRUNPERFENTRY_H



/************************* exported function prototypes ********************/
/* function declarations */
void init_hrSWRunPerfEntry(void);
void uninit_hrSWRunPerfEntry(void);
FindVarMethod var_hrSWRunPerfEntry;

#endif /* HRSWRUNPERFENTRY_H */
